# !/usr/bin/python
# -*- coding:utf-8 -*-

# 权限
PERMISSION_TYPE_ORGANIZATION_MANAGEMENT = 'B01000000'  # 组织管理
PERMISSION_TYPE_USER_MANAGEMENT = 'B01010000'  # 用户管理
PERMISSION_TYPE_ROLE_MANAGEMENT = 'B01020000'  # 角色管理
PERMISSION_TYPE_MEMBER_MANAGEMENT = 'B01030000'  # 会员
PERMISSION_TYPE_SOURCE_MANAGEMENT = 'B01040000'  # 来源管理
# 问卷管理
PERMISSION_TYPE_QUESTIONNAIRE_MANAGEMENT = 'B02000000'  # 问卷管理
PERMISSION_TYPE_QUESTIONNAIRE_RELEASE_MANAGEMENT = 'B02010000'  # 问卷发布
PERMISSION_TYPE_QUESTIONNAIRE_ACTIVITY_MANAGEMENT = 'B02020000'  # 活动列表

# 车型维护
PERMISSION_TYPE_VEHICLE_MANAGEMENT = 'B03000000'  # 车型维护
PERMISSION_TYPE_VEHICLE_RELEASE_MANAGEMENT = 'B03020000'  # 车型发布

# 积分管理
PERMISSION_TYPE_INTEGRAL_MANAGEMENT = 'B04000000'  # 积分管理
PERMISSION_TYPE_INTEGRAL_QUERY_MANAGEMENT = 'B04010000'  # 积分查询
PERMISSION_TYPE_INTEGRAL_AWARD_MANAGEMENT = 'B04020000'  # 积分奖励
PERMISSION_TYPE_INTEGRAL_EXCHANGE_MANAGEMENT = 'B04030000'  # 积分兑换
PERMISSION_TYPE_INTEGRAL_ORDER_MANAGEMENT = 'B04040000'  # 订单管理

# 小程序管理
PERMISSION_TYPE_MINIAPP_MANAGEMENT = 'B05000000'  # 小程序设置

PERMISSION_TYPE_MINIAPP_SUBJECT_BANK_MANAGEMENT = 'B05010000'  # 题库管理
PERMISSION_TYPE_MINIAPP_SUBJECT_DIFFICULTY_MANAGEMENT = 'B05010100'  # 难度管理
PERMISSION_TYPE_MINIAPP_SUBJECT_CATEGORY_MANAGEMENT = 'B05010200'  # 类别管理
PERMISSION_TYPE_MINIAPP_SUBJECT_DIMENSION_MANAGEMENT = 'B05010300'  # 维度管理
PERMISSION_TYPE_MINIAPP_SUBJECT_MANAGEMENT = 'B05010400'  # 题目管理
PERMISSION_TYPE_MINIAPP_SUBJECT_DRAW_MANAGEMENT = 'B05010500'  # 抽题管理
PERMISSION_TYPE_MINIAPP_GAME_MANAGEMENT = 'B05020000'  # 游戏管理
PERMISSION_TYPE_MINIAPP_GAME_DAN_GRADE_MANAGEMENT = 'B05020100'  # 段位管理
PERMISSION_TYPE_MINIAPP_GAME_CHECKPOINT_MANAGEMENT = 'B05020200'  # 关卡管理
PERMISSION_TYPE_MINIAPP_GAME_DIAMOND_MANAGEMENT = 'B05020300'  # 钻石管理
PERMISSION_TYPE_MINIAPP_GAME_BANK_MANAGEMENT = 'B05020400'  # 金库设置

PERMISSION_TYPE_MINIAPP_RACE_MANAGEMENT = 'B06000000'  # 竞赛活动管理
PERMISSION_TYPE_MINIAPP_RACE_ADD_OR_EDIT_MANAGEMENT = 'B06060000'  # 新增/编辑活动管理
PERMISSION_TYPE_MINIAPP_RACE_SUBJECT_MANAGEMENT = 'B06010000'  # 竞赛题库管理
PERMISSION_TYPE_MINIAPP_RACE_LEVEL_MANAGEMENT = 'B06020000'  # 竞赛关卡管理
PERMISSION_TYPE_MINIAPP_RACE_RULES_MANAGEMENT = 'B06030000'  # 竞赛抽题规则管理
PERMISSION_TYPE_MINIAPP_LOTTERY_DRAW_MANAGEMENT = 'B06040000'  # 竞赛红包管理
PERMISSION_TYPE_MINIAPP_UNIT_MANAGER_MANAGEMENT = 'B06050000'  # 单位管理
PERMISSION_TYPE_MINIAPP_RACE_REPORT_SITUATION = 'B06000001'  # 竞赛活动报表
PERMISSION_TYPE_MINIAPP_RACE_REPORT_EXECUTION = 'B06000002'  # 竞赛执行报表（单位报表）

# 报表
PERMISSION_TYPE_REPORT_MANAGEMENT = 'B80000000'  # 统计报表

PERMISSION_TYPE_REPORT_CONCLUSION_MANAGEMENT = 'B80100000'  # 总结报表
PERMISSION_TYPE_REPORT_LEARNING_SITUATION_MANAGEMENT = 'B80101000'  # 学习状况统计
PERMISSION_TYPE_REPORT_LEARNING_TENDENCY_MANAGEMENT = 'B80102000'  # 学习趋势统计

PERMISSION_TYPE_REPORT_SUBJECT_BANK_MANAGEMENT = 'B80200000'  # 题库报表
PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_MANAGEMENT = 'B80201000'  # 题目分析查看
PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_EXPORT = 'B80201001'  # 题目分析导出
PERMISSION_TYPE_REPORT_SUBJECT_PARAMETER_MANAGEMENT = 'B80202000'  # 题库参数分析

PERMISSION_TYPE_REPORT_EXECUTIVE_MANAGEMENT = 'B80300000'  # 执行报表
PERMISSION_TYPE_REPORT_EXECUTIVE_DIRECT_MANAGEMENT = 'B80301000'  # 引流效果分析

# 其他
PERMISSION_TYPE_SYSTEM_OTHER_MANAGEMENT = 'B900000000'  # 其他
PERMISSION_TYPE_SYSTEM_DOCKING_MANAGEMENT = 'B901000000'  # 获取接入安全信息

# 所有权限
ALL_PERMISSION_TYPE_LIST = [
    PERMISSION_TYPE_ORGANIZATION_MANAGEMENT,
    PERMISSION_TYPE_USER_MANAGEMENT,
    PERMISSION_TYPE_ROLE_MANAGEMENT,
    PERMISSION_TYPE_MEMBER_MANAGEMENT,
    PERMISSION_TYPE_QUESTIONNAIRE_MANAGEMENT,
    PERMISSION_TYPE_QUESTIONNAIRE_RELEASE_MANAGEMENT,
    PERMISSION_TYPE_QUESTIONNAIRE_ACTIVITY_MANAGEMENT,
    PERMISSION_TYPE_VEHICLE_MANAGEMENT,
    PERMISSION_TYPE_VEHICLE_RELEASE_MANAGEMENT,
    PERMISSION_TYPE_INTEGRAL_MANAGEMENT,
    PERMISSION_TYPE_INTEGRAL_QUERY_MANAGEMENT,
    PERMISSION_TYPE_INTEGRAL_AWARD_MANAGEMENT,
    PERMISSION_TYPE_INTEGRAL_EXCHANGE_MANAGEMENT,
    PERMISSION_TYPE_INTEGRAL_ORDER_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_SUBJECT_BANK_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_SUBJECT_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_SUBJECT_CATEGORY_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_SUBJECT_DIFFICULTY_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_SUBJECT_DIMENSION_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_GAME_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_UNIT_MANAGER_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_GAME_DAN_GRADE_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_GAME_CHECKPOINT_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_GAME_DIAMOND_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_GAME_BANK_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_RACE_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_RACE_ADD_OR_EDIT_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_RACE_REPORT_SITUATION,
    PERMISSION_TYPE_MINIAPP_RACE_REPORT_EXECUTION,
    PERMISSION_TYPE_MINIAPP_RACE_SUBJECT_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_RACE_LEVEL_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_RACE_RULES_MANAGEMENT,
    PERMISSION_TYPE_MINIAPP_LOTTERY_DRAW_MANAGEMENT,
    PERMISSION_TYPE_REPORT_MANAGEMENT,
    PERMISSION_TYPE_REPORT_CONCLUSION_MANAGEMENT,
    PERMISSION_TYPE_REPORT_LEARNING_SITUATION_MANAGEMENT,
    PERMISSION_TYPE_REPORT_LEARNING_TENDENCY_MANAGEMENT,
    PERMISSION_TYPE_REPORT_SUBJECT_BANK_MANAGEMENT,
    PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_MANAGEMENT,
    PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_EXPORT,
    PERMISSION_TYPE_REPORT_SUBJECT_PARAMETER_MANAGEMENT,
    PERMISSION_TYPE_REPORT_EXECUTIVE_MANAGEMENT,
    PERMISSION_TYPE_REPORT_EXECUTIVE_DIRECT_MANAGEMENT,
    PERMISSION_TYPE_SYSTEM_OTHER_MANAGEMENT,
    PERMISSION_TYPE_SYSTEM_DOCKING_MANAGEMENT
]

ALL_PERMISSION_TYPE_DICT = {
    PERMISSION_TYPE_ORGANIZATION_MANAGEMENT: '组织管理',
    PERMISSION_TYPE_USER_MANAGEMENT: '用户管理',
    PERMISSION_TYPE_ROLE_MANAGEMENT: '角色管理',
    PERMISSION_TYPE_MEMBER_MANAGEMENT: '会员管理',
    PERMISSION_TYPE_QUESTIONNAIRE_MANAGEMENT: '问卷管理',
    PERMISSION_TYPE_QUESTIONNAIRE_RELEASE_MANAGEMENT: '问卷发布',
    PERMISSION_TYPE_QUESTIONNAIRE_ACTIVITY_MANAGEMENT: '活动列表',
    PERMISSION_TYPE_VEHICLE_MANAGEMENT: '车型维护',
    PERMISSION_TYPE_VEHICLE_RELEASE_MANAGEMENT: '车型发布',
    PERMISSION_TYPE_MINIAPP_MANAGEMENT: '小程序设置',
    PERMISSION_TYPE_INTEGRAL_MANAGEMENT: '积分管理',
    PERMISSION_TYPE_INTEGRAL_QUERY_MANAGEMENT: '积分查询',
    PERMISSION_TYPE_INTEGRAL_AWARD_MANAGEMENT: '积分奖励',
    PERMISSION_TYPE_INTEGRAL_EXCHANGE_MANAGEMENT: '兑换商城',
    PERMISSION_TYPE_MINIAPP_SUBJECT_BANK_MANAGEMENT: '题库管理',
    PERMISSION_TYPE_MINIAPP_SUBJECT_DIFFICULTY_MANAGEMENT: '难度管理',
    PERMISSION_TYPE_MINIAPP_SUBJECT_CATEGORY_MANAGEMENT: '类别管理',
    PERMISSION_TYPE_MINIAPP_SUBJECT_DIMENSION_MANAGEMENT: '维度管理',
    PERMISSION_TYPE_MINIAPP_SUBJECT_MANAGEMENT: '题目管理',
    PERMISSION_TYPE_MINIAPP_SUBJECT_DRAW_MANAGEMENT: '抽题管理',
    PERMISSION_TYPE_MINIAPP_GAME_MANAGEMENT: '游戏管理',
    PERMISSION_TYPE_MINIAPP_GAME_DAN_GRADE_MANAGEMENT: '段位管理',
    PERMISSION_TYPE_MINIAPP_GAME_CHECKPOINT_MANAGEMENT: '关卡管理',
    PERMISSION_TYPE_MINIAPP_GAME_DIAMOND_MANAGEMENT: '钻石管理',
    PERMISSION_TYPE_MINIAPP_GAME_BANK_MANAGEMENT: '金库设置',
    PERMISSION_TYPE_MINIAPP_RACE_MANAGEMENT: '竞赛活动管理',
    PERMISSION_TYPE_MINIAPP_RACE_ADD_OR_EDIT_MANAGEMENT: "新增/编辑活动管理",
    PERMISSION_TYPE_MINIAPP_RACE_REPORT_SITUATION: '竞赛活动报表',
    PERMISSION_TYPE_MINIAPP_RACE_REPORT_EXECUTION: '竞赛执行报表',
    PERMISSION_TYPE_MINIAPP_RACE_SUBJECT_MANAGEMENT: '竞赛题库管理',
    PERMISSION_TYPE_MINIAPP_RACE_LEVEL_MANAGEMENT: '竞赛关卡管理',
    PERMISSION_TYPE_MINIAPP_RACE_RULES_MANAGEMENT: '竞赛抽题规则管理',
    PERMISSION_TYPE_MINIAPP_LOTTERY_DRAW_MANAGEMENT: '竞赛红包管理',
    PERMISSION_TYPE_MINIAPP_UNIT_MANAGER_MANAGEMENT: '单位管理',
    PERMISSION_TYPE_REPORT_MANAGEMENT: '统计报表',
    PERMISSION_TYPE_REPORT_CONCLUSION_MANAGEMENT: '总结报表',
    PERMISSION_TYPE_REPORT_LEARNING_SITUATION_MANAGEMENT: '学习状况统计',
    PERMISSION_TYPE_REPORT_LEARNING_TENDENCY_MANAGEMENT: '学习趋势统计',
    PERMISSION_TYPE_REPORT_SUBJECT_BANK_MANAGEMENT: '题库报表',
    PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_MANAGEMENT: '题目分析查看',
    PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_EXPORT: '题目分析导出',
    PERMISSION_TYPE_REPORT_SUBJECT_PARAMETER_MANAGEMENT: '题库参数分析',
    PERMISSION_TYPE_REPORT_EXECUTIVE_MANAGEMENT: '执行报表',
    PERMISSION_TYPE_REPORT_EXECUTIVE_DIRECT_MANAGEMENT: '引流效果分析',
    PERMISSION_TYPE_SYSTEM_OTHER_MANAGEMENT: '其他',
    PERMISSION_TYPE_SYSTEM_DOCKING_MANAGEMENT: '获取安全接入信息'
}

# 可供分配的用户权限
ALL_BACKOFFICE_ASSIGNABLE_PERMISSION_TYPE_DICT = {
    PERMISSION_TYPE_ORGANIZATION_MANAGEMENT: [
        PERMISSION_TYPE_USER_MANAGEMENT,
        PERMISSION_TYPE_ROLE_MANAGEMENT,
        PERMISSION_TYPE_MEMBER_MANAGEMENT
    ],
    # PERMISSION_TYPE_QUESTIONNAIRE_MANAGEMENT: [
    #     PERMISSION_TYPE_QUESTIONNAIRE_RELEASE_MANAGEMENT,
    #     PERMISSION_TYPE_QUESTIONNAIRE_ACTIVITY_MANAGEMENT
    # ],
    # PERMISSION_TYPE_VEHICLE_MANAGEMENT: [
    #     PERMISSION_TYPE_VEHICLE_MANAGEMENT,
    #     PERMISSION_TYPE_VEHICLE_RELEASE_MANAGEMENT
    # ],
    # PERMISSION_TYPE_INTEGRAL_MANAGEMENT: [
    #     PERMISSION_TYPE_INTEGRAL_QUERY_MANAGEMENT,
    #     PERMISSION_TYPE_INTEGRAL_AWARD_MANAGEMENT,
    #     PERMISSION_TYPE_INTEGRAL_EXCHANGE_MANAGEMENT
    # ],
    PERMISSION_TYPE_MINIAPP_MANAGEMENT: [
        # PERMISSION_TYPE_MINIAPP_SUBJECT_DIFFICULTY_MANAGEMENT,
        # PERMISSION_TYPE_MINIAPP_SUBJECT_CATEGORY_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_SUBJECT_DIMENSION_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_SUBJECT_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_SUBJECT_DRAW_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_GAME_DAN_GRADE_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_GAME_CHECKPOINT_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_GAME_DIAMOND_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_GAME_BANK_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_RACE_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_RACE_ADD_OR_EDIT_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_RACE_REPORT_SITUATION,
        PERMISSION_TYPE_MINIAPP_RACE_REPORT_EXECUTION,
        PERMISSION_TYPE_MINIAPP_RACE_SUBJECT_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_RACE_LEVEL_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_RACE_RULES_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_LOTTERY_DRAW_MANAGEMENT,
        PERMISSION_TYPE_MINIAPP_UNIT_MANAGER_MANAGEMENT

    ],
    PERMISSION_TYPE_REPORT_MANAGEMENT: [
        PERMISSION_TYPE_REPORT_LEARNING_SITUATION_MANAGEMENT,
        PERMISSION_TYPE_REPORT_LEARNING_TENDENCY_MANAGEMENT,
        PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_MANAGEMENT,
        PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_EXPORT,
        PERMISSION_TYPE_REPORT_SUBJECT_PARAMETER_MANAGEMENT,
        PERMISSION_TYPE_REPORT_EXECUTIVE_DIRECT_MANAGEMENT
    ],
    PERMISSION_TYPE_SYSTEM_OTHER_MANAGEMENT: [
        PERMISSION_TYPE_SYSTEM_DOCKING_MANAGEMENT
    ]
}

# 报表查看权限
REVIEW_REPORT_PERMS_LIST = [
    PERMISSION_TYPE_REPORT_MANAGEMENT,
    PERMISSION_TYPE_REPORT_CONCLUSION_MANAGEMENT,
    PERMISSION_TYPE_REPORT_LEARNING_SITUATION_MANAGEMENT,
    PERMISSION_TYPE_REPORT_LEARNING_TENDENCY_MANAGEMENT,
    PERMISSION_TYPE_REPORT_SUBJECT_BANK_MANAGEMENT,
    PERMISSION_TYPE_REPORT_SUBJECT_ANALYZE_MANAGEMENT,
    PERMISSION_TYPE_REPORT_SUBJECT_PARAMETER_MANAGEMENT,
    PERMISSION_TYPE_REPORT_EXECUTIVE_MANAGEMENT,
    PERMISSION_TYPE_REPORT_EXECUTIVE_DIRECT_MANAGEMENT
]
