# !/usr/bin/python
# -*- coding:utf-8 -*-


# 系统上传文件类别
CATEGORY_UPLOAD_FILE_IMG_MSG_PUSH = 1  # 消息推送图片
CATEGORY_UPLOAD_FILE_IMG_SUBJECT = 2  # 题目图片
CATEGORY_UPLOAD_FILE_IMG_PRESENT = 3  # 礼品图片
CATEGORY_UPLOAD_FILE_IMG_TXT = 4  # 富文本图片
CATEGORY_UPLOAD_FILE_IMG_GAME_DAN_GRADE = 5  # 段位图片
CATEGORY_UPLOAD_FILE_IMG_GAME_MEMBER_SOURCE_QR = 6  # 用户来源二维码
CATEGORY_CERTIFICATE_UE = 9  # UEditor
CATEGORY_UPLOAD_FILE_RACE = 10  # 竞赛活动图片
CATEGORY_UPLOAD_FILE_OTHER = 99  # 其他图片
CATEGORY_UPLOAD_FILE_LIST = [
    CATEGORY_UPLOAD_FILE_IMG_MSG_PUSH,
    CATEGORY_UPLOAD_FILE_IMG_SUBJECT,
    CATEGORY_UPLOAD_FILE_IMG_PRESENT,
    CATEGORY_UPLOAD_FILE_IMG_TXT,
    CATEGORY_UPLOAD_FILE_IMG_GAME_DAN_GRADE,
    CATEGORY_UPLOAD_FILE_OTHER
]
CATEGORY_UPLOAD_FILE_DICT = {
    CATEGORY_UPLOAD_FILE_IMG_MSG_PUSH: '消息推送图片',
    CATEGORY_UPLOAD_FILE_IMG_SUBJECT: '题目图片',
    CATEGORY_UPLOAD_FILE_IMG_PRESENT: '礼品图片',
    CATEGORY_UPLOAD_FILE_IMG_TXT: '富文本图片',
    CATEGORY_UPLOAD_FILE_IMG_GAME_DAN_GRADE: '段位图片',
    CATEGORY_UPLOAD_FILE_IMG_GAME_MEMBER_SOURCE_QR: '用户来源二维码',
    CATEGORY_UPLOAD_FILE_OTHER: '其他'
}

# 用户状态
STATUS_USER_ACTIVE = 1
STATUS_USER_INACTIVE = 2
STATUS_USER_LIST = [STATUS_USER_ACTIVE, STATUS_USER_INACTIVE]
STATUS_USER_DICT = {
    STATUS_USER_ACTIVE: '活动的',
    STATUS_USER_INACTIVE: '锁定的'
}

# 检索条件定义模块
MODULE_SEARCH_CONDITION_SITUATION_MEMBER_TIMES = 801  # 答题人次趋势
MODULE_SEARCH_CONDITION_SITUATION_MEMBER_ACTIVE = 802  # 公民活跃度
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY = 803  # 答题正确率趋势
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_SCIENCE = 804  # 答题正确率趋势-科学观念与方法
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_MATH = 805  # 答题正确率趋势-数学与信息
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_MATERIAL = 806  # 答题正确率趋势-物质与能量
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_LIFE = 807  # 答题正确率趋势-生命与健康
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ENVIRONMENT = 808  # 答题正确率趋势-地球与环境
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ENGINEER = 809  # 答题正确率趋势-工程与技术
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_TECHNOLOGY = 810  # 答题正确率趋势-科技与社会
MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ABILITY = 811  # 答题正确率趋势-能力与发展
MODULE_SEARCH_CONDITION_TENDENCY_SUBJECT_QUANTITY = 812  # 答对题目数分布
MODULE_SEARCH_CONDITION_TENDENCY_SUBJECT_ANALYSIS_DIMENSION = 813  # 公民科学素质雷达图
MODULE_SEARCH_CONDITION_TENDENCY_SUBJECT_PARAMETERS_COMPARE = 814  # 科学素质题库参数比较分析
MODULE_SEARCH_CONDITION_SHARED_EXAM_RESULT = 815  # 答题结果分享统计
MODULE_SEARCH_CONDITION_SHARED_FRIEND_FIGHT = 816  # 好友对战分享统计
MODULE_SEARCH_CONDITION_SHARED_OTHERS = 817  # 其他页面分享统计

MODULE_SEARCH_CONDITION_SUBJECT_ANALYSIS = 999  # 题目分析
MODULE_SEARCH_CONDITION_LIST = [
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY,
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_SCIENCE,
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_MATH,
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_MATERIAL,
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_LIFE,
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ENVIRONMENT,
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ENGINEER,
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_TECHNOLOGY,
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ABILITY,
    MODULE_SEARCH_CONDITION_SUBJECT_ANALYSIS
]
MODULE_SEARCH_CONDITION_DICT = {
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY: '答题正确率趋势',
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_SCIENCE: '答题正确率趋势-科学观念与方法',
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_MATH: '答题正确率趋势-数学与信息',
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_MATERIAL: '答题正确率趋势-物质与能量',
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_LIFE: '答题正确率趋势-生命与健康',
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ENVIRONMENT: ' 答题正确率趋势-地球与环境',
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ENGINEER: '答题正确率趋势-工程与技术',
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_TECHNOLOGY: '答题正确率趋势-科技与社会',
    MODULE_SEARCH_CONDITION_TENDENCY_ACCURACY_KNOWLEDGE_ABILITY: '# 答题正确率趋势-能力与发展'

}

# 性别
SEX_NONE = 0
SEX_MALE = 1
SEX_FEMALE = 2
SEX_LIST = [SEX_NONE, SEX_MALE, SEX_FEMALE]
SEX_DICT = {
    SEX_NONE: '无',
    SEX_MALE: '男',
    SEX_FEMALE: '女'
}

# 角色状态
STATUS_ROLE_ACTIVE = 1
STATUS_ROLE_INACTIVE = 2
STATUS_ROLE_LIST = [STATUS_ROLE_ACTIVE, STATUS_ROLE_INACTIVE]
STATUS_ROLE_DICT = {
    STATUS_ROLE_ACTIVE: '活动的',
    STATUS_ROLE_INACTIVE: '锁定的'
}

# 年龄段类型
TYPE_AGE_GROUP_NONE = 0  # 未知
TYPE_AGE_GROUP_YOUNG = 1  # 青年
TYPE_AGE_GROUP_MIDDLE = 2  # 中年
TYPE_AGE_GROUP_OLD = 3  # 老年
TYPE_AGE_GROUP_LIST = [
    TYPE_AGE_GROUP_NONE,
    TYPE_AGE_GROUP_YOUNG,
    TYPE_AGE_GROUP_MIDDLE,
    TYPE_AGE_GROUP_OLD
]
TYPE_AGE_GROUP_DICT = {
    TYPE_AGE_GROUP_NONE: '未知',
    TYPE_AGE_GROUP_YOUNG: '青年',
    TYPE_AGE_GROUP_MIDDLE: '中年',
    TYPE_AGE_GROUP_OLD: '老年'
}

# 学历类型
TYPE_EDUCATION_NONE = 0  # 未定义
TYPE_EDUCATION_JUNIOR = 1  # 初中及以下
TYPE_EDUCATION_SENIOR = 2  # 高中/中专/技校
TYPE_EDUCATION_COLLEGE = 3  # 大专
TYPE_EDUCATION_BACHELOR = 4  # 本科/学士
TYPE_EDUCATION_MASTER = 5  # 硕士及以上
TYPE_EDUCATION_LIST = [
    TYPE_EDUCATION_NONE,
    TYPE_EDUCATION_JUNIOR,
    TYPE_EDUCATION_SENIOR,
    TYPE_EDUCATION_COLLEGE,
    TYPE_EDUCATION_BACHELOR,
    TYPE_EDUCATION_MASTER
]
TYPE_EDUCATION_DICT = {
    TYPE_EDUCATION_NONE: '未定义',
    TYPE_EDUCATION_JUNIOR: '初中及以下',
    TYPE_EDUCATION_SENIOR: '高中/中专/技校',
    TYPE_EDUCATION_COLLEGE: '大专',
    TYPE_EDUCATION_BACHELOR: '本科/学士',
    TYPE_EDUCATION_MASTER: '硕士及以上'
}

# 会员群体
CATEGORY_MEMBER_NONE = 0  # 未选
CATEGORY_MEMBER_OFFICIAL = 1  # 领导干部及公务员
CATEGORY_MEMBER_LABOURER = 2  # 城镇劳动者
CATEGORY_MEMBER_PEASANT = 3  # 农民
CATEGORY_MEMBER_TEENAGER = 4  # 青少年
CATEGORY_MEMBER_COMMUNITY_RESIDENT = 5  # 社区居民
CATEGORY_MEMBER_LIST = [
    CATEGORY_MEMBER_NONE,
    CATEGORY_MEMBER_OFFICIAL,
    CATEGORY_MEMBER_LABOURER,
    CATEGORY_MEMBER_PEASANT,
    CATEGORY_MEMBER_TEENAGER,
    CATEGORY_MEMBER_COMMUNITY_RESIDENT
]
CATEGORY_MEMBER_DICT = {
    CATEGORY_MEMBER_NONE: '未选',
    CATEGORY_MEMBER_OFFICIAL: '领导干部及公务员',
    CATEGORY_MEMBER_LABOURER: '城镇劳动者',
    CATEGORY_MEMBER_PEASANT: '农民',
    CATEGORY_MEMBER_TEENAGER: '青少年',
    CATEGORY_MEMBER_COMMUNITY_RESIDENT: '社区居民'
}

# 会员来源
SOURCE_TYPE_MEMBER_OFFLINE = '1'  # 线下
SOURCE_TYPE_MEMBER_ONLINE = '2'  # 线上
SOURCE_TYPE_MEMBER_SCAN_QR = '3'  # 扫码
SOURCE_TYPE_MEMBER_SHARE = '4'  # 分享
SOURCE_TYPE_MEMBER_SEARCH = '5'  # 搜索
SOURCE_TYPE_MEMBER_SYSTEM = '99'  # 系统
SOURCE_TYPE_MEMBER_LIST = [
    SOURCE_TYPE_MEMBER_OFFLINE,
    SOURCE_TYPE_MEMBER_ONLINE,
    SOURCE_TYPE_MEMBER_SCAN_QR,
    SOURCE_TYPE_MEMBER_SHARE,
    SOURCE_TYPE_MEMBER_SEARCH,
    SOURCE_TYPE_MEMBER_SYSTEM
]
SOURCE_TYPE_MEMBER_DICT = {
    SOURCE_TYPE_MEMBER_OFFLINE: '线下',
    SOURCE_TYPE_MEMBER_ONLINE: '线上',
    SOURCE_TYPE_MEMBER_SCAN_QR: '扫码',
    SOURCE_TYPE_MEMBER_SHARE: '分享',
    SOURCE_TYPE_MEMBER_SEARCH: '搜索',
    SOURCE_TYPE_MEMBER_SYSTEM: '系统'
}

# 会员段位
TYPE_DAN_GRADE_ONE = 1  # 入门新手
TYPE_DAN_GRADE_TWO = 2  # 坚定磐石
TYPE_DAN_GRADE_THIRD = 3  # 无畏黑铁
TYPE_DAN_GRADE_FOUR = 4  # 勇敢青铜
TYPE_DAN_GRADE_FIVE = 5  # 秩序白银
TYPE_DAN_GRADE_SIX = 6  # 高贵黄金
TYPE_DAN_GRADE_SEVEN = 7  # 庄严白金
TYPE_DAN_GRADE_EIGHT = 8  # 奢华铂金
TYPE_DAN_GRADE_NINE = 9  # 光辉钻石
TYPE_DAN_GRADE_TEN = 10  # 一代宗师
TYPE_DAN_GRADE_ELEVEN = 11  # 车界传说
TYPE_DAN_GRADE_LIST = [
    TYPE_DAN_GRADE_ONE, TYPE_DAN_GRADE_TWO, TYPE_DAN_GRADE_THIRD, TYPE_DAN_GRADE_FOUR, TYPE_DAN_GRADE_FIVE,
    TYPE_DAN_GRADE_SIX, TYPE_DAN_GRADE_SEVEN, TYPE_DAN_GRADE_EIGHT, TYPE_DAN_GRADE_NINE, TYPE_DAN_GRADE_TEN,
    TYPE_DAN_GRADE_ELEVEN
]
TYPE_DAN_GRADE_DICT = {
    TYPE_DAN_GRADE_ONE: u'初来乍到',
    TYPE_DAN_GRADE_TWO: u'新手入门',
    TYPE_DAN_GRADE_THIRD: u'初出茅庐',
    TYPE_DAN_GRADE_FOUR: u'逐步成长',
    TYPE_DAN_GRADE_FIVE: u'驾轻就熟',
    TYPE_DAN_GRADE_SIX: u'身手不凡',
    TYPE_DAN_GRADE_SEVEN: u'名不虚传',
    TYPE_DAN_GRADE_EIGHT: u'炉火纯青',
    TYPE_DAN_GRADE_NINE: u'登峰造极',
    TYPE_DAN_GRADE_TEN: u'一代宗师',
    TYPE_DAN_GRADE_ELEVEN: u'最强王者'
}

# 会员星级
TYPE_STAR_GRADE_ZERO = 0  # 0颗星
TYPE_STAR_GRADE_ONE = 1  # 1颗星
TYPE_STAR_GRADE_TWO = 2  # 2颗星
TYPE_STAR_GRADE_THREE = 3  # 3颗星
TYPE_STAR_GRADE_FOUR = 4  # 4颗星
TYPE_STAR_GRADE_FIVE = 5  # 5颗星
TYPE_STAR_GRADE_LIST = [
    TYPE_STAR_GRADE_ONE, TYPE_STAR_GRADE_TWO, TYPE_STAR_GRADE_THREE, TYPE_STAR_GRADE_FOUR, TYPE_STAR_GRADE_FIVE
]
TYPE_STAR_GRADE_DICT = {
    TYPE_STAR_GRADE_ZERO: '0颗星', TYPE_STAR_GRADE_ONE: '1颗星', TYPE_STAR_GRADE_TWO: '2颗星',
    TYPE_STAR_GRADE_THREE: '3颗星', TYPE_STAR_GRADE_FOUR: '4颗星', TYPE_STAR_GRADE_FIVE: '5颗星'
}

# 星级段位映射关系
DAN_STAR_GRADE_MAPPING = {
    TYPE_DAN_GRADE_ONE: TYPE_STAR_GRADE_ONE,
    TYPE_DAN_GRADE_TWO: TYPE_STAR_GRADE_TWO,
    TYPE_DAN_GRADE_THIRD: TYPE_STAR_GRADE_THREE,
    TYPE_DAN_GRADE_FOUR: TYPE_STAR_GRADE_THREE,
    TYPE_DAN_GRADE_FIVE: TYPE_STAR_GRADE_THREE,
    TYPE_DAN_GRADE_SIX: TYPE_STAR_GRADE_FOUR,
    TYPE_DAN_GRADE_SEVEN: TYPE_STAR_GRADE_FOUR,
    TYPE_DAN_GRADE_EIGHT: TYPE_STAR_GRADE_FOUR,
    TYPE_DAN_GRADE_NINE: TYPE_STAR_GRADE_FOUR,
    TYPE_DAN_GRADE_TEN: TYPE_STAR_GRADE_FIVE,
    TYPE_DAN_GRADE_ELEVEN: TYPE_STAR_GRADE_FIVE
}

# 积分来源
SOURCE_MEMBER_INTEGRAL_ADMIN_UPDATE = 1  # 管理员修改
SOURCE_MEMBER_INTEGRAL_NOVICE = 2  # 新手欢迎奖励
SOURCE_MEMBER_INTEGRAL_PII = 3  # 完善个人信息奖励
SOURCE_MEMBER_INTEGRAL_FIRST_SURVEY = 4  # 首次答问卷奖励
SOURCE_MEMBER_INTEGRAL_FIRST_KNOWLEDGE_PK = 5  # 首次参与汽车知识PK奖励
SOURCE_MEMBER_INTEGRAL_LOGIN_EVERYDAY = 6  # 每日签到奖励
SOURCE_MEMBER_INTEGRAL_EVERY_SURVEY = 7  # 答问卷奖励(每份)
SOURCE_MEMBER_INTEGRAL_KNOWLEDGE_PK_EVERYDAY = 8  # 参与汽车知识PK(限每天一次)
SOURCE_MEMBER_INTEGRAL_USER_RETURN = 9  # 老用户回归(三天以上未登录)
SOURCE_MEMBER_INTEGRAL_LIST = [
    SOURCE_MEMBER_INTEGRAL_ADMIN_UPDATE,
    SOURCE_MEMBER_INTEGRAL_NOVICE,
    SOURCE_MEMBER_INTEGRAL_PII,
    SOURCE_MEMBER_INTEGRAL_FIRST_SURVEY,
    SOURCE_MEMBER_INTEGRAL_FIRST_KNOWLEDGE_PK,
    SOURCE_MEMBER_INTEGRAL_LOGIN_EVERYDAY,
    SOURCE_MEMBER_INTEGRAL_EVERY_SURVEY,
    SOURCE_MEMBER_INTEGRAL_KNOWLEDGE_PK_EVERYDAY,
    SOURCE_MEMBER_INTEGRAL_USER_RETURN
]
SOURCE_MEMBER_INTEGRAL_DICT = {
    SOURCE_MEMBER_INTEGRAL_ADMIN_UPDATE: '管理员修改',
    SOURCE_MEMBER_INTEGRAL_NOVICE: '新手欢迎奖励',
    SOURCE_MEMBER_INTEGRAL_PII: '完善个人信息奖励',
    SOURCE_MEMBER_INTEGRAL_FIRST_SURVEY: '首次答问卷奖励',
    SOURCE_MEMBER_INTEGRAL_FIRST_KNOWLEDGE_PK: '首次参与汽车知识PK奖励',
    SOURCE_MEMBER_INTEGRAL_LOGIN_EVERYDAY: '每日签到奖励',
    SOURCE_MEMBER_INTEGRAL_EVERY_SURVEY: '答问卷奖励(每份)',
    SOURCE_MEMBER_INTEGRAL_KNOWLEDGE_PK_EVERYDAY: '参与汽车知识PK(限每天一次)',
    SOURCE_MEMBER_INTEGRAL_USER_RETURN: '老用户回归(三天以上未签到)'
}

# 会员调研状态
STATUS_MEMBER_SURVEY_STARTED = 1  # 开始未完成
STATUS_MEMBER_SURVEY_NORMAL = 2  # 正常完成
STATUS_MEMBER_SURVEY_FILTERED = 3  # 被筛选
STATUS_MEMBER_SURVEY_QUOTA_FULLED = 4  # 配额满
STATUS_MEMBER_SURVEY_LIST = [
    STATUS_MEMBER_SURVEY_STARTED,
    STATUS_MEMBER_SURVEY_NORMAL,
    STATUS_MEMBER_SURVEY_FILTERED,
    STATUS_MEMBER_SURVEY_QUOTA_FULLED
]
STATUS_MEMBER_SURVEY_DICT = {
    STATUS_MEMBER_SURVEY_STARTED: '开始未完成',
    STATUS_MEMBER_SURVEY_NORMAL: '正常完成',
    STATUS_MEMBER_SURVEY_FILTERED: '被筛选',
    STATUS_MEMBER_SURVEY_QUOTA_FULLED: '配额满'
}

# 小游戏PK状态结果
STATUS_RESULT_GAME_PK_WIN = 1  # 胜利
STATUS_RESULT_GAME_PK_FAILED = 2  # 失败
STATUS_RESULT_GAME_PK_GIVE_UP = 3  # 放弃
STATUS_RESULT_GAME_PK_TIE_BREAK = 4  # 平局
STATUS_RESULT_GAME_PK_LIST = [
    STATUS_RESULT_GAME_PK_WIN,
    STATUS_RESULT_GAME_PK_FAILED,
    STATUS_RESULT_GAME_PK_GIVE_UP,
    STATUS_RESULT_GAME_PK_TIE_BREAK
]
STATUS_RESULT_GAME_PK_DICT = {
    STATUS_RESULT_GAME_PK_WIN: '胜利',
    STATUS_RESULT_GAME_PK_FAILED: '失败',
    STATUS_RESULT_GAME_PK_GIVE_UP: '放弃',
    STATUS_RESULT_GAME_PK_TIE_BREAK: '平局',
}

# 小游戏竞赛结果
STATUS_RESULT_CHECK_POINT_WIN = 1  # 成功
STATUS_RESULT_CHECK_POINT_FAILED = 2  # 失败
STATUS_RESULT_CHECK_POINT_GIVE_UP = 3  # 放弃
STATUS_RESULT_CHECK_POINT_LIST = [
    STATUS_RESULT_CHECK_POINT_WIN,
    STATUS_RESULT_CHECK_POINT_FAILED,
    STATUS_RESULT_CHECK_POINT_GIVE_UP
]
STATUS_RESULT_CHECK_POINT_DICT = {
    STATUS_RESULT_CHECK_POINT_WIN: '成功',
    STATUS_RESULT_CHECK_POINT_FAILED: '失败',
    STATUS_RESULT_CHECK_POINT_GIVE_UP: '放弃'
}

# 问卷状态
STATUS_QUESTIONNAIRE_ACTIVE = 1
STATUS_QUESTIONNAIRE_INACTIVE = 2
STATUS_QUESTIONNAIRE_LIST = [STATUS_QUESTIONNAIRE_ACTIVE, STATUS_QUESTIONNAIRE_INACTIVE]
STATUS_QUESTIONNAIRE_DICT = {
    STATUS_QUESTIONNAIRE_ACTIVE: '活动的',
    STATUS_QUESTIONNAIRE_INACTIVE: '锁定的'
}

# 推送类别
PUSH_CATEGORY_NOW = 1
PUSH_CATEGORY_DELAY = 2
PUSH_CATEGORY_LIST = [
    PUSH_CATEGORY_NOW, PUSH_CATEGORY_DELAY
]
PUSH_CATEGORY_DICT = {
    PUSH_CATEGORY_NOW: '立即发送',
    PUSH_CATEGORY_DELAY: '延时发送',
}

# 消息推送
STATUS_PULL_ACTION_WAIT_PUSH = 1
STATUS_PULL_ACTION_PUSHED = 2
STATUS_PULL_ACTION_PUSHED_SUCCESS = 3
STATUS_PULL_ACTION_PUSHED_FAIL = 4
STATUS_PULL_ACTION_LIST = [
    STATUS_PULL_ACTION_WAIT_PUSH, STATUS_PULL_ACTION_PUSHED, STATUS_PULL_ACTION_PUSHED_SUCCESS,
    STATUS_PULL_ACTION_PUSHED_FAIL
]
STATUS_PULL_ACTION_DICT = {
    STATUS_PULL_ACTION_WAIT_PUSH: '等待推送',
    STATUS_PULL_ACTION_PUSHED: '已推送',
    STATUS_PULL_ACTION_PUSHED_SUCCESS: '推送成功',
    STATUS_PULL_ACTION_PUSHED_FAIL: '推送失败'
}

# 接受方式
PUSH_RECEIVE_WECHAT = 1
PUSH_RECEIVE_EMAIL = 2
PUSH_RECEIVE_SMS = 3
PUSH_RECEIVE_LIST = [
    PUSH_RECEIVE_WECHAT,
    PUSH_RECEIVE_EMAIL,
    PUSH_RECEIVE_SMS
]
PUSH_RECEIVE_DICT = {
    PUSH_RECEIVE_WECHAT: '微信',
    PUSH_RECEIVE_EMAIL: '邮箱',
    PUSH_RECEIVE_SMS: '短信息'
}

# 属性信息
CATEGORY_ATTRIBUTE_INFO_TYPE = 1  # 车辆类型
CATEGORY_ATTRIBUTE_INFO_BRAND = 2  # 车辆品牌
CATEGORY_ATTRIBUTE_INFO_SERIES = 3  # 车辆系列
CATEGORY_ATTRIBUTE_INFO_CFG = 4  # 车辆配置
CATEGORY_ATTRIBUTE_INFO_COLOUR = 5  # 车辆颜色
CATEGORY_ATTRIBUTE_INFO_DISPLACEMENT = 6  # 排量
CATEGORY_ATTRIBUTE_INFO_LIST = [
    CATEGORY_ATTRIBUTE_INFO_TYPE,
    CATEGORY_ATTRIBUTE_INFO_BRAND,
    CATEGORY_ATTRIBUTE_INFO_SERIES,
    CATEGORY_ATTRIBUTE_INFO_CFG,
    CATEGORY_ATTRIBUTE_INFO_COLOUR,
    CATEGORY_ATTRIBUTE_INFO_DISPLACEMENT
]
CATEGORY_ATTRIBUTE_INFO_DICT = {
    CATEGORY_ATTRIBUTE_INFO_TYPE: '类型',
    CATEGORY_ATTRIBUTE_INFO_BRAND: '品牌',
    CATEGORY_ATTRIBUTE_INFO_SERIES: '系列',
    CATEGORY_ATTRIBUTE_INFO_CFG: '配置',
    CATEGORY_ATTRIBUTE_INFO_COLOUR: '颜色',
    CATEGORY_ATTRIBUTE_INFO_DISPLACEMENT: '排量'
}

# 车型状态
STATUS_VEHICLE_ACTIVE = 1
STATUS_VEHICLE_INACTIVE = 2
STATUS_VEHICLE_LIST = [STATUS_VEHICLE_ACTIVE, STATUS_VEHICLE_INACTIVE]
STATUS_VEHICLE_DICT = {
    STATUS_VEHICLE_ACTIVE: '启用的',
    STATUS_VEHICLE_INACTIVE: '禁用的'
}

# 礼品类别
CATEGORY_PRESENT_DISCOUNT_COUPON = 1  # 优惠券
CATEGORY_PRESENT_REAL_GIFT = 2  # 实物礼品
CATEGORY_PRESENT_WECHAT_LUCKY_MONEY = 3  # 微信红包
CATEGORY_PRESENT_LIST = [
    CATEGORY_PRESENT_DISCOUNT_COUPON,
    CATEGORY_PRESENT_REAL_GIFT,
    CATEGORY_PRESENT_WECHAT_LUCKY_MONEY
]
CATEGORY_PRESENT_DICT = {
    CATEGORY_PRESENT_DISCOUNT_COUPON: '优惠券',
    CATEGORY_PRESENT_REAL_GIFT: '实物礼品',
    CATEGORY_PRESENT_WECHAT_LUCKY_MONEY: '微信红包'
}

# 礼品状态
STATUS_PRESENT_ACTIVE = 1
STATUS_PRESENT_INACTIVE = 2
STATUS_PRESENT_LIST = [STATUS_PRESENT_ACTIVE, STATUS_PRESENT_INACTIVE]
STATUS_PRESENT_DICT = {
    STATUS_PRESENT_ACTIVE: '活动的',
    STATUS_PRESENT_INACTIVE: '锁定的'
}

# 优惠券状态
STATUS_DISCOUNT_COUPON_UNUSED = 1  # 未使用
STATUS_DISCOUNT_COUPON_USED = 2  # 已使用
STATUS_DISCOUNT_COUPON_EXPIRED = 3  # 已过期
STATUS_DISCOUNT_COUPON_LIST = [
    STATUS_DISCOUNT_COUPON_UNUSED,
    STATUS_DISCOUNT_COUPON_USED,
    STATUS_DISCOUNT_COUPON_EXPIRED
]
STATUS_DISCOUNT_COUPON_DICT = {
    STATUS_DISCOUNT_COUPON_UNUSED: '未使用',
    STATUS_DISCOUNT_COUPON_USED: '已使用',
    STATUS_DISCOUNT_COUPON_EXPIRED: '已过期'
}

# 订单状态
STATUS_EXCHANGE_ORDER_UNSHIPPED = 1  # 未发货
STATUS_EXCHANGE_ORDER_SHIPPED = 2  # 已发货
STATUS_EXCHANGE_ORDER_CLOSED = 3  # 已关闭
STATUS_EXCHANGE_ORDER_LIST = [
    STATUS_EXCHANGE_ORDER_UNSHIPPED,
    STATUS_EXCHANGE_ORDER_SHIPPED,
    STATUS_EXCHANGE_ORDER_CLOSED]
STATUS_EXCHANGE_ORDER_DICT = {
    STATUS_EXCHANGE_ORDER_UNSHIPPED: '未发货',
    STATUS_EXCHANGE_ORDER_SHIPPED: '已发货',
    STATUS_EXCHANGE_ORDER_CLOSED: '已关闭'
}

# 承运人信息
CODE_CARRIER_EMS = 1  # EMS
CODE_CARRIER_SF = 2  # 顺丰速递
CODE_CARRIER_YT = 3  # 圆通速递
CODE_CARRIER_STO = 4  # 申通速递
CODE_CARRIER_ZTO = 5  # 中通速递
CODE_CARRIER_LIST = [
    CODE_CARRIER_EMS,
    CODE_CARRIER_SF,
    CODE_CARRIER_YT,
    CODE_CARRIER_STO,
    CODE_CARRIER_ZTO
]
CODE_CARRIER_DICT = {
    CODE_CARRIER_EMS: 'EMS',
    CODE_CARRIER_SF: '顺丰速递',
    CODE_CARRIER_YT: '圆通速递',
    CODE_CARRIER_STO: '申通速递',
    CODE_CARRIER_ZTO: '中通速递'
}

# 题目用途
CATEGORY_SUBJECT_GENERAL = 1  # 一般
CATEGORY_SUBJECT_BENCHMARK = 2  # 基准测试
CATEGORY_SUBJECT_GRADUATION = 3  # 毕业测试
CATEGORY_SUBJECT_LIST = [
    CATEGORY_SUBJECT_GENERAL,
    CATEGORY_SUBJECT_BENCHMARK,
    CATEGORY_SUBJECT_GRADUATION
]
CATEGORY_SUBJECT_DICT = {
    CATEGORY_SUBJECT_GENERAL: '一般',
    CATEGORY_SUBJECT_BENCHMARK: '基准测试',
    CATEGORY_SUBJECT_GRADUATION: '毕业测试'
}

# 题目难度
CODE_SUBJECT_DIFFICULTY_SIMPLE = 1  # 简单
CODE_SUBJECT_DIFFICULTY_MEDIUM = 2  # 中等
CODE_SUBJECT_DIFFICULTY_HIGH = 3  # 困难
CODE_SUBJECT_DIFFICULTY_FORTH = 4  # 难度4
CODE_SUBJECT_DIFFICULTY_FIFTH = 5  # 难度5
CODE_SUBJECT_DIFFICULTY_LIST = [
    CODE_SUBJECT_DIFFICULTY_SIMPLE,
    CODE_SUBJECT_DIFFICULTY_MEDIUM,
    CODE_SUBJECT_DIFFICULTY_HIGH,
    CODE_SUBJECT_DIFFICULTY_FORTH,
    CODE_SUBJECT_DIFFICULTY_FIFTH
]
CODE_SUBJECT_DIFFICULTY_DICT = {
    CODE_SUBJECT_DIFFICULTY_SIMPLE: u'非常简单',
    CODE_SUBJECT_DIFFICULTY_MEDIUM: u'简单',
    CODE_SUBJECT_DIFFICULTY_HIGH: u'一般',
    CODE_SUBJECT_DIFFICULTY_FORTH: u'困难',
    CODE_SUBJECT_DIFFICULTY_FIFTH: u'非常困难'
}

# 题目类别
CATEGORY_SUBJECT_KNOWLEDGE_SCIENCE = 1
CATEGORY_SUBJECT_KNOWLEDGE_MATH = 2
CATEGORY_SUBJECT_KNOWLEDGE_MATERIAL = 3
CATEGORY_SUBJECT_KNOWLEDGE_LIFE = 4
CATEGORY_SUBJECT_KNOWLEDGE_ENVIRONMENT = 5
CATEGORY_SUBJECT_KNOWLEDGE_ENGINEER = 6
CATEGORY_SUBJECT_KNOWLEDGE_TECHNOLOGY = 7
CATEGORY_SUBJECT_KNOWLEDGE_ABILITY = 8

CATEGORY_SUBJECT_KNOWLEDGE_LIST = [
    CATEGORY_SUBJECT_KNOWLEDGE_SCIENCE,
    CATEGORY_SUBJECT_KNOWLEDGE_MATH,
    CATEGORY_SUBJECT_KNOWLEDGE_MATERIAL,
    CATEGORY_SUBJECT_KNOWLEDGE_LIFE,
    CATEGORY_SUBJECT_KNOWLEDGE_ENVIRONMENT,
    CATEGORY_SUBJECT_KNOWLEDGE_ENGINEER,
    CATEGORY_SUBJECT_KNOWLEDGE_TECHNOLOGY,
    CATEGORY_SUBJECT_KNOWLEDGE_ABILITY
]
CATEGORY_SUBJECT_KNOWLEDGE_DICT = {
    CATEGORY_SUBJECT_KNOWLEDGE_SCIENCE: u'科学观念与方法',
    CATEGORY_SUBJECT_KNOWLEDGE_MATH: u'数学与信息',
    CATEGORY_SUBJECT_KNOWLEDGE_MATERIAL: u'物质与能量',
    CATEGORY_SUBJECT_KNOWLEDGE_LIFE: u'生命与健康',
    CATEGORY_SUBJECT_KNOWLEDGE_ENVIRONMENT: u'地球与环境',
    CATEGORY_SUBJECT_KNOWLEDGE_ENGINEER: u'工程与技术',
    CATEGORY_SUBJECT_KNOWLEDGE_TECHNOLOGY: u'科技与社会',
    CATEGORY_SUBJECT_KNOWLEDGE_ABILITY: u'能力与发展'
}

# 题目状态
STATUS_SUBJECT_ACTIVE = 1
STATUS_SUBJECT_INACTIVE = 2
STATUS_SUBJECT_LIST = [STATUS_SUBJECT_ACTIVE, STATUS_SUBJECT_INACTIVE]
STATUS_SUBJECT_DICT = {
    STATUS_SUBJECT_ACTIVE: '启用',
    STATUS_SUBJECT_INACTIVE: '禁用'
}

# 题库类别
CATEGORY_SUBJECT_BANK_FIGHT = 1  # 对战赛
CATEGORY_SUBJECT_BANK_CONTEST = 2  # 竞赛
CATEGORY_SUBJECT_BANK_LIST = [
    CATEGORY_SUBJECT_BANK_FIGHT,
    CATEGORY_SUBJECT_BANK_CONTEST
]
CATEGORY_SUBJECT_BANK_DICT = {
    CATEGORY_SUBJECT_BANK_FIGHT: '对战赛',
    CATEGORY_SUBJECT_BANK_CONTEST: '竞赛'
}

# 会员钻石奖励
SOURCE_MEMBER_DIAMOND_ADMIN_UPDATE = 1  # 管理员修改
SOURCE_MEMBER_DIAMOND_NOVICE = 2  # 新手欢迎奖励
SOURCE_MEMBER_DIAMOND_FIRST_PK = 3  # 首次小程序PK
SOURCE_MEMBER_DIAMOND_FIRST_WIN = 4  # 首次小程序PK获胜
SOURCE_MEMBER_DIAMOND_LOGIN_EVERYDAY = 5  # 每日登录奖励
SOURCE_MEMBER_DIAMOND_WIN_STREAK_TIMES = 6  # 连胜起始次数
SOURCE_MEMBER_DIAMOND_WIN_STREAK_AWARD_START = 7  # 连胜起始奖励数
SOURCE_MEMBER_DIAMOND_WIN_STREAK_AWARD_APPEND = 8  # 每次连胜增加钻石
SOURCE_MEMBER_DIAMOND_USER_RETURN = 9  # 老用户回归(三天以上未登录)
SOURCE_MEMBER_DIAMOND_PK_VICTORY = 10  # PK获胜
SOURCE_MEMBER_DIAMOND_PK_FAILURE = 11  # PK失败
SOURCE_MEMBER_DIAMOND_PK_ENTRANCE_FEE = 12  # PK入场费
SOURCE_MEMBER_DIAMOND_PK_ENTRANCE_FEE_RETURN = 13  # PK入场费返还
SOURCE_MEMBER_DIAMOND_VAULT_REWARD = 14  # 金库奖励

SOURCE_MEMBER_DIAMOND_DAILY_SHARE = 15  # 每日分享
SOURCE_MEMBER_DIAMOND_DAILY_SHARE_TIMES_LIMIT = 16  # 每日分享次数阀值
SOURCE_MEMBER_DIAMOND_DAILY_RANKING = 17  # 每日排行榜
SOURCE_MEMBER_DIAMOND_DAILY_RANKING_VALUE_LIMIT = 18  # 每日排行榜名次阀值

SOURCE_MEMBER_DIAMOND_LIST = [
    SOURCE_MEMBER_DIAMOND_ADMIN_UPDATE,
    SOURCE_MEMBER_DIAMOND_NOVICE,
    SOURCE_MEMBER_DIAMOND_FIRST_PK,
    SOURCE_MEMBER_DIAMOND_FIRST_WIN,
    SOURCE_MEMBER_DIAMOND_LOGIN_EVERYDAY,
    SOURCE_MEMBER_DIAMOND_WIN_STREAK_TIMES,
    SOURCE_MEMBER_DIAMOND_WIN_STREAK_AWARD_START,
    SOURCE_MEMBER_DIAMOND_WIN_STREAK_AWARD_APPEND,
    SOURCE_MEMBER_DIAMOND_USER_RETURN,
    SOURCE_MEMBER_DIAMOND_PK_VICTORY,
    SOURCE_MEMBER_DIAMOND_PK_FAILURE,
    SOURCE_MEMBER_DIAMOND_PK_ENTRANCE_FEE,
    SOURCE_MEMBER_DIAMOND_PK_ENTRANCE_FEE_RETURN,
    SOURCE_MEMBER_DIAMOND_VAULT_REWARD,
    SOURCE_MEMBER_DIAMOND_DAILY_SHARE,
    SOURCE_MEMBER_DIAMOND_DAILY_SHARE_TIMES_LIMIT,
    SOURCE_MEMBER_DIAMOND_DAILY_RANKING,
    SOURCE_MEMBER_DIAMOND_DAILY_RANKING_VALUE_LIMIT
]
SOURCE_MEMBER_DIAMOND_DICT = {
    SOURCE_MEMBER_DIAMOND_ADMIN_UPDATE: '管理员修改',
    SOURCE_MEMBER_DIAMOND_NOVICE: '新手欢迎奖励',
    SOURCE_MEMBER_DIAMOND_FIRST_PK: '首次PK',
    SOURCE_MEMBER_DIAMOND_FIRST_WIN: '首次获胜',
    SOURCE_MEMBER_DIAMOND_LOGIN_EVERYDAY: '每日登录',
    SOURCE_MEMBER_DIAMOND_WIN_STREAK_TIMES: '起始次数',
    SOURCE_MEMBER_DIAMOND_WIN_STREAK_AWARD_START: '起始奖励钻石',
    SOURCE_MEMBER_DIAMOND_WIN_STREAK_AWARD_APPEND: '每次连胜增加钻石',
    SOURCE_MEMBER_DIAMOND_USER_RETURN: '老用户回归(三天以上未登录)',
    SOURCE_MEMBER_DIAMOND_PK_VICTORY: '游戏PK获胜',
    SOURCE_MEMBER_DIAMOND_PK_FAILURE: '游戏PK失败',
    SOURCE_MEMBER_DIAMOND_PK_ENTRANCE_FEE: '游戏PK入场费',
    SOURCE_MEMBER_DIAMOND_PK_ENTRANCE_FEE_RETURN: '游戏PK入场费返还',
    SOURCE_MEMBER_DIAMOND_VAULT_REWARD: u'金库奖励',
    SOURCE_MEMBER_DIAMOND_DAILY_SHARE: '每日分享',
    SOURCE_MEMBER_DIAMOND_DAILY_SHARE_TIMES_LIMIT: '每日分享次数',
    SOURCE_MEMBER_DIAMOND_DAILY_RANKING: '每日排行榜',
    SOURCE_MEMBER_DIAMOND_DAILY_RANKING_VALUE_LIMIT: '每日排行榜名次'
}

# 知识维度
DIMENSION_SUBJECT_SCIENCE_IDEA = 1
DIMENSION_SUBJECT_SCIENCE_STUDY = 2
DIMENSION_SUBJECT_SCIENCE_PRACTICE = 3

DIMENSION_SUBJECT_LIST = [
    DIMENSION_SUBJECT_SCIENCE_IDEA,
    DIMENSION_SUBJECT_SCIENCE_STUDY,
    DIMENSION_SUBJECT_SCIENCE_PRACTICE,
]

DIMENSION_SUBJECT_DICT = {
    DIMENSION_SUBJECT_SCIENCE_IDEA: u'科学事实概念',
    DIMENSION_SUBJECT_SCIENCE_STUDY: u'科学研究本质',
    DIMENSION_SUBJECT_SCIENCE_PRACTICE: u'科学知识运用',
}

# 一级知识点
KNOWLEDGE_FIRST_LEVEL_1 = 1
KNOWLEDGE_FIRST_LEVEL_2 = 2
KNOWLEDGE_FIRST_LEVEL_3 = 3
KNOWLEDGE_FIRST_LEVEL_4 = 4
KNOWLEDGE_FIRST_LEVEL_5 = 5
KNOWLEDGE_FIRST_LEVEL_6 = 6
KNOWLEDGE_FIRST_LEVEL_7 = 7
KNOWLEDGE_FIRST_LEVEL_8 = 8
KNOWLEDGE_FIRST_LEVEL_9 = 9
KNOWLEDGE_FIRST_LEVEL_10 = 10
KNOWLEDGE_FIRST_LEVEL_11 = 11
KNOWLEDGE_FIRST_LEVEL_12 = 12
KNOWLEDGE_FIRST_LEVEL_13 = 13
KNOWLEDGE_FIRST_LEVEL_14 = 14
KNOWLEDGE_FIRST_LEVEL_15 = 15
KNOWLEDGE_FIRST_LEVEL_16 = 16
KNOWLEDGE_FIRST_LEVEL_17 = 17
KNOWLEDGE_FIRST_LEVEL_18 = 18
KNOWLEDGE_FIRST_LEVEL_19 = 19
KNOWLEDGE_FIRST_LEVEL_20 = 20
KNOWLEDGE_FIRST_LEVEL_21 = 21
KNOWLEDGE_FIRST_LEVEL_22 = 22
KNOWLEDGE_FIRST_LEVEL_23 = 23
KNOWLEDGE_FIRST_LEVEL_24 = 24
KNOWLEDGE_FIRST_LEVEL_25 = 25
KNOWLEDGE_FIRST_LEVEL_26 = 26
KNOWLEDGE_FIRST_LEVEL_27 = 27
KNOWLEDGE_FIRST_LEVEL_28 = 28
KNOWLEDGE_FIRST_LEVEL_29 = 29
KNOWLEDGE_FIRST_LEVEL_30 = 30
KNOWLEDGE_FIRST_LEVEL_31 = 31
KNOWLEDGE_FIRST_LEVEL_32 = 32

KNOWLEDGE_FIRST_LEVEL_LIST = [
    KNOWLEDGE_FIRST_LEVEL_1, KNOWLEDGE_FIRST_LEVEL_2, KNOWLEDGE_FIRST_LEVEL_3, KNOWLEDGE_FIRST_LEVEL_4,
    KNOWLEDGE_FIRST_LEVEL_5, KNOWLEDGE_FIRST_LEVEL_6, KNOWLEDGE_FIRST_LEVEL_7, KNOWLEDGE_FIRST_LEVEL_8,
    KNOWLEDGE_FIRST_LEVEL_9, KNOWLEDGE_FIRST_LEVEL_10, KNOWLEDGE_FIRST_LEVEL_11, KNOWLEDGE_FIRST_LEVEL_12,
    KNOWLEDGE_FIRST_LEVEL_13, KNOWLEDGE_FIRST_LEVEL_14, KNOWLEDGE_FIRST_LEVEL_15, KNOWLEDGE_FIRST_LEVEL_16,
    KNOWLEDGE_FIRST_LEVEL_17, KNOWLEDGE_FIRST_LEVEL_18, KNOWLEDGE_FIRST_LEVEL_19, KNOWLEDGE_FIRST_LEVEL_20,
    KNOWLEDGE_FIRST_LEVEL_21, KNOWLEDGE_FIRST_LEVEL_22, KNOWLEDGE_FIRST_LEVEL_23, KNOWLEDGE_FIRST_LEVEL_24,
    KNOWLEDGE_FIRST_LEVEL_25, KNOWLEDGE_FIRST_LEVEL_26, KNOWLEDGE_FIRST_LEVEL_27, KNOWLEDGE_FIRST_LEVEL_28,
    KNOWLEDGE_FIRST_LEVEL_29, KNOWLEDGE_FIRST_LEVEL_30, KNOWLEDGE_FIRST_LEVEL_31, KNOWLEDGE_FIRST_LEVEL_32
]

KNOWLEDGE_FIRST_LEVEL_DICT = {
    KNOWLEDGE_FIRST_LEVEL_1: u'科学观念',
    KNOWLEDGE_FIRST_LEVEL_2: u'科学方法',
    KNOWLEDGE_FIRST_LEVEL_3: u'数与形',
    KNOWLEDGE_FIRST_LEVEL_4: u'符号与推理',
    KNOWLEDGE_FIRST_LEVEL_5: u'恒定与变化',
    KNOWLEDGE_FIRST_LEVEL_6: u'不确定性',
    KNOWLEDGE_FIRST_LEVEL_7: u'计算与信息',
    KNOWLEDGE_FIRST_LEVEL_8: u'身边的物质',
    KNOWLEDGE_FIRST_LEVEL_9: u'物质的构成',
    KNOWLEDGE_FIRST_LEVEL_10: u'运动与相互作用',
    KNOWLEDGE_FIRST_LEVEL_11: u'能与能源',
    KNOWLEDGE_FIRST_LEVEL_12: u'生物多样性',
    KNOWLEDGE_FIRST_LEVEL_13: u'分子与细胞',
    KNOWLEDGE_FIRST_LEVEL_14: u'遗传与进化',
    KNOWLEDGE_FIRST_LEVEL_15: u'稳态与控制',
    KNOWLEDGE_FIRST_LEVEL_16: u'生物与环境',
    KNOWLEDGE_FIRST_LEVEL_17: u'疾病防控与健康',
    KNOWLEDGE_FIRST_LEVEL_18: u'生物技术与工程',
    KNOWLEDGE_FIRST_LEVEL_19: u'宇宙中的地球',
    KNOWLEDGE_FIRST_LEVEL_20: u'地球系统',
    KNOWLEDGE_FIRST_LEVEL_21: u'地球和人类活动',
    KNOWLEDGE_FIRST_LEVEL_22: u'现代制造技术',
    KNOWLEDGE_FIRST_LEVEL_23: u'前沿高新技术',
    KNOWLEDGE_FIRST_LEVEL_24: u'大型科技工程',
    KNOWLEDGE_FIRST_LEVEL_25: u'民生科技热点',
    KNOWLEDGE_FIRST_LEVEL_26: u'科学技术与人类文明',
    KNOWLEDGE_FIRST_LEVEL_27: u'科学技术及其社会运行',
    KNOWLEDGE_FIRST_LEVEL_28: u'科学技术与社会发展',
    KNOWLEDGE_FIRST_LEVEL_29: u'能力',
    KNOWLEDGE_FIRST_LEVEL_30: u'科学研究的过程与重要环节',
    KNOWLEDGE_FIRST_LEVEL_31: u'技术设计的过程与重要环节',
    KNOWLEDGE_FIRST_LEVEL_32: u'科学决策的过程与方法'

}

# 二级知识点
KNOWLEDGE_SECOND_LEVEL_1 = 1
KNOWLEDGE_SECOND_LEVEL_2 = 2
KNOWLEDGE_SECOND_LEVEL_3 = 3
KNOWLEDGE_SECOND_LEVEL_4 = 4
KNOWLEDGE_SECOND_LEVEL_5 = 5
KNOWLEDGE_SECOND_LEVEL_6 = 6
KNOWLEDGE_SECOND_LEVEL_7 = 7
KNOWLEDGE_SECOND_LEVEL_8 = 8
KNOWLEDGE_SECOND_LEVEL_9 = 9
KNOWLEDGE_SECOND_LEVEL_10 = 10
KNOWLEDGE_SECOND_LEVEL_11 = 11
KNOWLEDGE_SECOND_LEVEL_12 = 12
KNOWLEDGE_SECOND_LEVEL_13 = 13
KNOWLEDGE_SECOND_LEVEL_14 = 14
KNOWLEDGE_SECOND_LEVEL_15 = 15
KNOWLEDGE_SECOND_LEVEL_16 = 16
KNOWLEDGE_SECOND_LEVEL_17 = 17
KNOWLEDGE_SECOND_LEVEL_18 = 18
KNOWLEDGE_SECOND_LEVEL_19 = 19
KNOWLEDGE_SECOND_LEVEL_20 = 20
KNOWLEDGE_SECOND_LEVEL_21 = 21
KNOWLEDGE_SECOND_LEVEL_22 = 22
KNOWLEDGE_SECOND_LEVEL_23 = 23
KNOWLEDGE_SECOND_LEVEL_24 = 24
KNOWLEDGE_SECOND_LEVEL_25 = 25
KNOWLEDGE_SECOND_LEVEL_26 = 26
KNOWLEDGE_SECOND_LEVEL_27 = 27
KNOWLEDGE_SECOND_LEVEL_28 = 28
KNOWLEDGE_SECOND_LEVEL_29 = 29
KNOWLEDGE_SECOND_LEVEL_30 = 30
KNOWLEDGE_SECOND_LEVEL_31 = 31
KNOWLEDGE_SECOND_LEVEL_32 = 32
KNOWLEDGE_SECOND_LEVEL_33 = 33
KNOWLEDGE_SECOND_LEVEL_34 = 34
KNOWLEDGE_SECOND_LEVEL_35 = 35
KNOWLEDGE_SECOND_LEVEL_36 = 36
KNOWLEDGE_SECOND_LEVEL_37 = 37
KNOWLEDGE_SECOND_LEVEL_38 = 38
KNOWLEDGE_SECOND_LEVEL_39 = 39
KNOWLEDGE_SECOND_LEVEL_40 = 40
KNOWLEDGE_SECOND_LEVEL_41 = 41
KNOWLEDGE_SECOND_LEVEL_42 = 42
KNOWLEDGE_SECOND_LEVEL_43 = 43
KNOWLEDGE_SECOND_LEVEL_44 = 44
KNOWLEDGE_SECOND_LEVEL_45 = 45
KNOWLEDGE_SECOND_LEVEL_46 = 46
KNOWLEDGE_SECOND_LEVEL_47 = 47
KNOWLEDGE_SECOND_LEVEL_48 = 48
KNOWLEDGE_SECOND_LEVEL_49 = 49
KNOWLEDGE_SECOND_LEVEL_50 = 50
KNOWLEDGE_SECOND_LEVEL_51 = 51
KNOWLEDGE_SECOND_LEVEL_52 = 52
KNOWLEDGE_SECOND_LEVEL_53 = 53
KNOWLEDGE_SECOND_LEVEL_54 = 54
KNOWLEDGE_SECOND_LEVEL_55 = 55
KNOWLEDGE_SECOND_LEVEL_56 = 56
KNOWLEDGE_SECOND_LEVEL_57 = 57
KNOWLEDGE_SECOND_LEVEL_58 = 58
KNOWLEDGE_SECOND_LEVEL_59 = 59
KNOWLEDGE_SECOND_LEVEL_60 = 60
KNOWLEDGE_SECOND_LEVEL_61 = 61
KNOWLEDGE_SECOND_LEVEL_62 = 62
KNOWLEDGE_SECOND_LEVEL_63 = 63
KNOWLEDGE_SECOND_LEVEL_64 = 64
KNOWLEDGE_SECOND_LEVEL_65 = 65
KNOWLEDGE_SECOND_LEVEL_66 = 66
KNOWLEDGE_SECOND_LEVEL_67 = 67
KNOWLEDGE_SECOND_LEVEL_68 = 68
KNOWLEDGE_SECOND_LEVEL_69 = 69
KNOWLEDGE_SECOND_LEVEL_70 = 70
KNOWLEDGE_SECOND_LEVEL_71 = 71
KNOWLEDGE_SECOND_LEVEL_72 = 72
KNOWLEDGE_SECOND_LEVEL_73 = 73
KNOWLEDGE_SECOND_LEVEL_74 = 74
KNOWLEDGE_SECOND_LEVEL_75 = 75
KNOWLEDGE_SECOND_LEVEL_76 = 76
KNOWLEDGE_SECOND_LEVEL_77 = 77
KNOWLEDGE_SECOND_LEVEL_78 = 78
KNOWLEDGE_SECOND_LEVEL_79 = 79
KNOWLEDGE_SECOND_LEVEL_80 = 80
KNOWLEDGE_SECOND_LEVEL_81 = 81
KNOWLEDGE_SECOND_LEVEL_82 = 82
KNOWLEDGE_SECOND_LEVEL_83 = 83
KNOWLEDGE_SECOND_LEVEL_84 = 84
KNOWLEDGE_SECOND_LEVEL_85 = 85
KNOWLEDGE_SECOND_LEVEL_86 = 86
KNOWLEDGE_SECOND_LEVEL_87 = 87
KNOWLEDGE_SECOND_LEVEL_88 = 88
KNOWLEDGE_SECOND_LEVEL_89 = 89
KNOWLEDGE_SECOND_LEVEL_90 = 90
KNOWLEDGE_SECOND_LEVEL_91 = 91
KNOWLEDGE_SECOND_LEVEL_92 = 92
KNOWLEDGE_SECOND_LEVEL_93 = 93
KNOWLEDGE_SECOND_LEVEL_94 = 94
KNOWLEDGE_SECOND_LEVEL_95 = 95
KNOWLEDGE_SECOND_LEVEL_96 = 96
KNOWLEDGE_SECOND_LEVEL_97 = 97
KNOWLEDGE_SECOND_LEVEL_98 = 98
KNOWLEDGE_SECOND_LEVEL_99 = 99
KNOWLEDGE_SECOND_LEVEL_100 = 100
KNOWLEDGE_SECOND_LEVEL_101 = 101
KNOWLEDGE_SECOND_LEVEL_102 = 102
KNOWLEDGE_SECOND_LEVEL_103 = 103
KNOWLEDGE_SECOND_LEVEL_104 = 104
KNOWLEDGE_SECOND_LEVEL_105 = 105
KNOWLEDGE_SECOND_LEVEL_106 = 106
KNOWLEDGE_SECOND_LEVEL_107 = 107
KNOWLEDGE_SECOND_LEVEL_108 = 108
KNOWLEDGE_SECOND_LEVEL_109 = 109

KNOWLEDGE_SECOND_LEVEL_LIST = [
    KNOWLEDGE_SECOND_LEVEL_1,
    KNOWLEDGE_SECOND_LEVEL_2,
    KNOWLEDGE_SECOND_LEVEL_3,
    KNOWLEDGE_SECOND_LEVEL_4,
    KNOWLEDGE_SECOND_LEVEL_5,
    KNOWLEDGE_SECOND_LEVEL_6,
    KNOWLEDGE_SECOND_LEVEL_7,
    KNOWLEDGE_SECOND_LEVEL_8,
    KNOWLEDGE_SECOND_LEVEL_9,
    KNOWLEDGE_SECOND_LEVEL_10,
    KNOWLEDGE_SECOND_LEVEL_11,
    KNOWLEDGE_SECOND_LEVEL_12,
    KNOWLEDGE_SECOND_LEVEL_13,
    KNOWLEDGE_SECOND_LEVEL_14,
    KNOWLEDGE_SECOND_LEVEL_15,
    KNOWLEDGE_SECOND_LEVEL_16,
    KNOWLEDGE_SECOND_LEVEL_17,
    KNOWLEDGE_SECOND_LEVEL_18,
    KNOWLEDGE_SECOND_LEVEL_19,
    KNOWLEDGE_SECOND_LEVEL_20,
    KNOWLEDGE_SECOND_LEVEL_21,
    KNOWLEDGE_SECOND_LEVEL_22,
    KNOWLEDGE_SECOND_LEVEL_23,
    KNOWLEDGE_SECOND_LEVEL_24,
    KNOWLEDGE_SECOND_LEVEL_25,
    KNOWLEDGE_SECOND_LEVEL_26,
    KNOWLEDGE_SECOND_LEVEL_27,
    KNOWLEDGE_SECOND_LEVEL_28,
    KNOWLEDGE_SECOND_LEVEL_29,
    KNOWLEDGE_SECOND_LEVEL_30,
    KNOWLEDGE_SECOND_LEVEL_31,
    KNOWLEDGE_SECOND_LEVEL_32,
    KNOWLEDGE_SECOND_LEVEL_33,
    KNOWLEDGE_SECOND_LEVEL_34,
    KNOWLEDGE_SECOND_LEVEL_35,
    KNOWLEDGE_SECOND_LEVEL_36,
    KNOWLEDGE_SECOND_LEVEL_37,
    KNOWLEDGE_SECOND_LEVEL_38,
    KNOWLEDGE_SECOND_LEVEL_39,
    KNOWLEDGE_SECOND_LEVEL_40,
    KNOWLEDGE_SECOND_LEVEL_41,
    KNOWLEDGE_SECOND_LEVEL_42,
    KNOWLEDGE_SECOND_LEVEL_43,
    KNOWLEDGE_SECOND_LEVEL_44,
    KNOWLEDGE_SECOND_LEVEL_45,
    KNOWLEDGE_SECOND_LEVEL_46,
    KNOWLEDGE_SECOND_LEVEL_47,
    KNOWLEDGE_SECOND_LEVEL_48,
    KNOWLEDGE_SECOND_LEVEL_49,
    KNOWLEDGE_SECOND_LEVEL_50,
    KNOWLEDGE_SECOND_LEVEL_51,
    KNOWLEDGE_SECOND_LEVEL_52,
    KNOWLEDGE_SECOND_LEVEL_53,
    KNOWLEDGE_SECOND_LEVEL_54,
    KNOWLEDGE_SECOND_LEVEL_55,
    KNOWLEDGE_SECOND_LEVEL_56,
    KNOWLEDGE_SECOND_LEVEL_57,
    KNOWLEDGE_SECOND_LEVEL_58,
    KNOWLEDGE_SECOND_LEVEL_59,
    KNOWLEDGE_SECOND_LEVEL_60,
    KNOWLEDGE_SECOND_LEVEL_61,
    KNOWLEDGE_SECOND_LEVEL_62,
    KNOWLEDGE_SECOND_LEVEL_63,
    KNOWLEDGE_SECOND_LEVEL_64,
    KNOWLEDGE_SECOND_LEVEL_65,
    KNOWLEDGE_SECOND_LEVEL_66,
    KNOWLEDGE_SECOND_LEVEL_67,
    KNOWLEDGE_SECOND_LEVEL_68,
    KNOWLEDGE_SECOND_LEVEL_69,
    KNOWLEDGE_SECOND_LEVEL_70,
    KNOWLEDGE_SECOND_LEVEL_71,
    KNOWLEDGE_SECOND_LEVEL_72,
    KNOWLEDGE_SECOND_LEVEL_73,
    KNOWLEDGE_SECOND_LEVEL_74,
    KNOWLEDGE_SECOND_LEVEL_75,
    KNOWLEDGE_SECOND_LEVEL_76,
    KNOWLEDGE_SECOND_LEVEL_77,
    KNOWLEDGE_SECOND_LEVEL_78,
    KNOWLEDGE_SECOND_LEVEL_79,
    KNOWLEDGE_SECOND_LEVEL_80,
    KNOWLEDGE_SECOND_LEVEL_81,
    KNOWLEDGE_SECOND_LEVEL_82,
    KNOWLEDGE_SECOND_LEVEL_83,
    KNOWLEDGE_SECOND_LEVEL_84,
    KNOWLEDGE_SECOND_LEVEL_85,
    KNOWLEDGE_SECOND_LEVEL_86,
    KNOWLEDGE_SECOND_LEVEL_87,
    KNOWLEDGE_SECOND_LEVEL_88,
    KNOWLEDGE_SECOND_LEVEL_89,
    KNOWLEDGE_SECOND_LEVEL_90,
    KNOWLEDGE_SECOND_LEVEL_91,
    KNOWLEDGE_SECOND_LEVEL_92,
    KNOWLEDGE_SECOND_LEVEL_93,
    KNOWLEDGE_SECOND_LEVEL_94,
    KNOWLEDGE_SECOND_LEVEL_95,
    KNOWLEDGE_SECOND_LEVEL_96,
    KNOWLEDGE_SECOND_LEVEL_97,
    KNOWLEDGE_SECOND_LEVEL_98,
    KNOWLEDGE_SECOND_LEVEL_99,
    KNOWLEDGE_SECOND_LEVEL_100,
    KNOWLEDGE_SECOND_LEVEL_101,
    KNOWLEDGE_SECOND_LEVEL_102,
    KNOWLEDGE_SECOND_LEVEL_103,
    KNOWLEDGE_SECOND_LEVEL_104,
    KNOWLEDGE_SECOND_LEVEL_105,
    KNOWLEDGE_SECOND_LEVEL_106,
    KNOWLEDGE_SECOND_LEVEL_107,
    KNOWLEDGE_SECOND_LEVEL_108,
    KNOWLEDGE_SECOND_LEVEL_109
]

KNOWLEDGE_SECOND_LEVEL_DICT = {
    KNOWLEDGE_SECOND_LEVEL_1: u'从自然本身理解自然',
    KNOWLEDGE_SECOND_LEVEL_2: u'用科学反对迷信',
    KNOWLEDGE_SECOND_LEVEL_3: u'证据、规律与理论',
    KNOWLEDGE_SECOND_LEVEL_4: u'科学探究过程',
    KNOWLEDGE_SECOND_LEVEL_5: u'观察和实验',
    KNOWLEDGE_SECOND_LEVEL_6: u'推理',
    KNOWLEDGE_SECOND_LEVEL_7: u'理想化方法',
    KNOWLEDGE_SECOND_LEVEL_8: u'数与数之间的关系',
    KNOWLEDGE_SECOND_LEVEL_9: u'函数',
    KNOWLEDGE_SECOND_LEVEL_10: u'数理统计',
    KNOWLEDGE_SECOND_LEVEL_11: u'排列与组合',
    KNOWLEDGE_SECOND_LEVEL_12: u'概率分布',
    KNOWLEDGE_SECOND_LEVEL_13: u'运筹学',
    KNOWLEDGE_SECOND_LEVEL_14: u'计算机',
    KNOWLEDGE_SECOND_LEVEL_15: u'大数据时代',
    KNOWLEDGE_SECOND_LEVEL_16: u'物质的形态与变化',
    KNOWLEDGE_SECOND_LEVEL_17: u'物理性质',
    KNOWLEDGE_SECOND_LEVEL_18: u'空气',
    KNOWLEDGE_SECOND_LEVEL_19: u'水和常见溶液',
    KNOWLEDGE_SECOND_LEVEL_20: u'常见化合物',
    KNOWLEDGE_SECOND_LEVEL_21: u'常见物质与人类健康',
    KNOWLEDGE_SECOND_LEVEL_22: u'构成物质的微粒',
    KNOWLEDGE_SECOND_LEVEL_23: u'化学元素',
    KNOWLEDGE_SECOND_LEVEL_24: u'化学反应',
    KNOWLEDGE_SECOND_LEVEL_25: u'机械运动和力',
    KNOWLEDGE_SECOND_LEVEL_26: u'声和光',
    KNOWLEDGE_SECOND_LEVEL_27: u'电和磁',
    KNOWLEDGE_SECOND_LEVEL_28: u'能量及其转化和转移',
    KNOWLEDGE_SECOND_LEVEL_29: u'机械能',
    KNOWLEDGE_SECOND_LEVEL_30: u'内能和热',
    KNOWLEDGE_SECOND_LEVEL_31: u'电磁能',
    KNOWLEDGE_SECOND_LEVEL_32: u'能量守恒定律',
    KNOWLEDGE_SECOND_LEVEL_33: u'能源和可持续发展',
    KNOWLEDGE_SECOND_LEVEL_34: u'生物多样性和生物的分类',
    KNOWLEDGE_SECOND_LEVEL_35: u'植物',
    KNOWLEDGE_SECOND_LEVEL_36: u'动物',
    KNOWLEDGE_SECOND_LEVEL_37: u'细菌、真菌和病毒',
    KNOWLEDGE_SECOND_LEVEL_38: u'生物入侵',
    KNOWLEDGE_SECOND_LEVEL_39: u'生物多样性与人类',
    KNOWLEDGE_SECOND_LEVEL_40: u'细胞的分子基础',
    KNOWLEDGE_SECOND_LEVEL_41: u'细胞的结构',
    KNOWLEDGE_SECOND_LEVEL_42: u'细胞的代谢',
    KNOWLEDGE_SECOND_LEVEL_43: u'细胞的生长、分裂和分化',
    KNOWLEDGE_SECOND_LEVEL_44: u'遗传与变异',
    KNOWLEDGE_SECOND_LEVEL_45: u'遗传物质',
    KNOWLEDGE_SECOND_LEVEL_46: u'遗传的基本规律',
    KNOWLEDGE_SECOND_LEVEL_47: u'遗传与环境',
    KNOWLEDGE_SECOND_LEVEL_48: u'遗传病与致病基因',
    KNOWLEDGE_SECOND_LEVEL_49: u'生物进化',
    KNOWLEDGE_SECOND_LEVEL_50: u'消化与吸收',
    KNOWLEDGE_SECOND_LEVEL_51: u'血液与循环',
    KNOWLEDGE_SECOND_LEVEL_52: u'气体交换与呼吸',
    KNOWLEDGE_SECOND_LEVEL_53: u'神经、感官与神经调节',
    KNOWLEDGE_SECOND_LEVEL_54: u'免疫系统与免疫调节',
    KNOWLEDGE_SECOND_LEVEL_55: u'植物的结构、生殖与营养',
    KNOWLEDGE_SECOND_LEVEL_56: u'植物的调控系统',
    KNOWLEDGE_SECOND_LEVEL_57: u'生存与环境',
    KNOWLEDGE_SECOND_LEVEL_58: u'生态系统的结构和功能',
    KNOWLEDGE_SECOND_LEVEL_59: u'人类面临的生态问题',
    KNOWLEDGE_SECOND_LEVEL_60: u'科学健身',
    KNOWLEDGE_SECOND_LEVEL_61: u'精神与心理健康',
    KNOWLEDGE_SECOND_LEVEL_62: u'均衡饮食与营养',
    KNOWLEDGE_SECOND_LEVEL_63: u'食品安全',
    KNOWLEDGE_SECOND_LEVEL_64: u'生活中的健康',
    KNOWLEDGE_SECOND_LEVEL_65: u'传染病',
    KNOWLEDGE_SECOND_LEVEL_66: u'职业疾病',
    KNOWLEDGE_SECOND_LEVEL_67: u'日常急救避险常识',
    KNOWLEDGE_SECOND_LEVEL_68: u'基因工程',
    KNOWLEDGE_SECOND_LEVEL_69: u'宇宙和天体',
    KNOWLEDGE_SECOND_LEVEL_70: u'地球和太阳系',
    KNOWLEDGE_SECOND_LEVEL_71: u'地球的演化',
    KNOWLEDGE_SECOND_LEVEL_72: u'地球的圈层结构',
    KNOWLEDGE_SECOND_LEVEL_73: u'地质运动与地貌演化',
    KNOWLEDGE_SECOND_LEVEL_74: u'地球表面的水',
    KNOWLEDGE_SECOND_LEVEL_75: u'天气和气候',
    KNOWLEDGE_SECOND_LEVEL_76: u'自然资源',
    KNOWLEDGE_SECOND_LEVEL_77: u'自然灾害',
    KNOWLEDGE_SECOND_LEVEL_78: u'生态破坏与环境问题',
    KNOWLEDGE_SECOND_LEVEL_79: u'地图与地理信息技术',
    KNOWLEDGE_SECOND_LEVEL_80: u'新材料',
    KNOWLEDGE_SECOND_LEVEL_81: u'移动智能终端',
    KNOWLEDGE_SECOND_LEVEL_82: u'移动通信',
    KNOWLEDGE_SECOND_LEVEL_83: u'卫星导航技术',
    KNOWLEDGE_SECOND_LEVEL_84: u'仿生技术',
    KNOWLEDGE_SECOND_LEVEL_85: u'人工智能',
    KNOWLEDGE_SECOND_LEVEL_86: u'虚拟现实技术',
    KNOWLEDGE_SECOND_LEVEL_87: u'3D 打印技术',
    KNOWLEDGE_SECOND_LEVEL_88: u'超导技术',
    KNOWLEDGE_SECOND_LEVEL_89: u'大数据与云计算',
    KNOWLEDGE_SECOND_LEVEL_90: u'中国载人航天工程',
    KNOWLEDGE_SECOND_LEVEL_91: u'探月工程',
    KNOWLEDGE_SECOND_LEVEL_92: u'智慧城市',
    KNOWLEDGE_SECOND_LEVEL_93: u'大飞机',
    KNOWLEDGE_SECOND_LEVEL_94: u'高速铁路',
    KNOWLEDGE_SECOND_LEVEL_95: u'核电站',
    KNOWLEDGE_SECOND_LEVEL_96: u'污水处理技术',
    KNOWLEDGE_SECOND_LEVEL_97: u'食品添加剂',
    KNOWLEDGE_SECOND_LEVEL_98: u'信息安全',
    KNOWLEDGE_SECOND_LEVEL_99: u'科学、技术、工程',
    KNOWLEDGE_SECOND_LEVEL_100: u'科学技术发展与人类文明进步',
    KNOWLEDGE_SECOND_LEVEL_101: u'科学技术研究规范',
    KNOWLEDGE_SECOND_LEVEL_102: u'科学技术的社会功能和复杂作用',
    KNOWLEDGE_SECOND_LEVEL_103: u'当代科技创新与社会发展',
    KNOWLEDGE_SECOND_LEVEL_104: u'科学能力及构成',
    KNOWLEDGE_SECOND_LEVEL_105: u'发展能力',
    KNOWLEDGE_SECOND_LEVEL_106: u'收集证据和数据',
    KNOWLEDGE_SECOND_LEVEL_107: u'技术设计的一般过程',
    KNOWLEDGE_SECOND_LEVEL_108: u'提出技术上潜在的解决方案',
    KNOWLEDGE_SECOND_LEVEL_109: u'科学决策'
}

ANSWER_LIMIT_NUMBER = 10

# 竞赛活动分类
CATEGORY_RACE_LOCAL = 1  # 本地
CATEGORY_RACE_REFER = 2  # 引用
CATEGORY_RACE_LIST = [
    CATEGORY_RACE_LOCAL,
    CATEGORY_RACE_REFER
]
CATEGORY_ACTIVITY_DICT = {
    CATEGORY_RACE_LOCAL: '本地',
    CATEGORY_RACE_REFER: '引用'
}

# 题目维度类别
CATEGORY_SUBJECT_DIMENSION_WEIGHT = 1  # 权重
CATEGORY_SUBJECT_DIMENSION_NUMERICAL = 2  # 数值
CATEGORY_SUBJECT_DIMENSION_OPTIONS = 3  # 选项涵盖
CATEGORY_SUBJECT_DIMENSION_WEIGHT_LIST = [
    CATEGORY_SUBJECT_DIMENSION_WEIGHT,
    CATEGORY_SUBJECT_DIMENSION_NUMERICAL,
    CATEGORY_SUBJECT_DIMENSION_OPTIONS
]
CATEGORY_SUBJECT_DIMENSION_WEIGHT_DICT = {
    CATEGORY_SUBJECT_DIMENSION_WEIGHT: '权重',
    CATEGORY_SUBJECT_DIMENSION_NUMERICAL: '数值',
    CATEGORY_SUBJECT_DIMENSION_OPTIONS: '选项涵盖'
}

# 题目维度状态
STATUS_SUBJECT_DIMENSION_ACTIVE = 1  # 活动的
STATUS_SUBJECT_DIMENSION_INACTIVE = 2  # 禁用的
STATUS_SUBJECT_DIMENSION_LIST = [
    STATUS_SUBJECT_DIMENSION_ACTIVE,
    STATUS_SUBJECT_DIMENSION_INACTIVE
]
STATUS_SUBJECT_DIMENSION_DICT = {
    STATUS_SUBJECT_DIMENSION_ACTIVE: '活动的',
    STATUS_SUBJECT_DIMENSION_INACTIVE: '禁用的'
}

# 题目类别状态
STATUS_SUBJECT_CATEGORY_ACTIVE = 1  # 有效的
STATUS_SUBJECT_CATEGORY_INACTIVE = 2  # 无效的
STATUS_SUBJECT_CATEGORY_LIST = [
    STATUS_SUBJECT_CATEGORY_ACTIVE,
    STATUS_SUBJECT_CATEGORY_INACTIVE
]
STATUS_SUBJECT_CATEGORY_DICT = {
    STATUS_SUBJECT_CATEGORY_ACTIVE: '有效的',
    STATUS_SUBJECT_CATEGORY_INACTIVE: '无效的'
}

# 题目难度状态
STATUS_SUBJECT_DIFFICULTY_ACTIVE = 1  # 有效的
STATUS_SUBJECT_DIFFICULTY_INACTIVE = 2  # 无效的
STATUS_SUBJECT_DIFFICULTY_LIST = [
    STATUS_SUBJECT_DIFFICULTY_ACTIVE,
    STATUS_SUBJECT_DIFFICULTY_INACTIVE
]
STATUS_SUBJECT_DIFFICULTY_DICT = {
    STATUS_SUBJECT_DIFFICULTY_ACTIVE: '有效的',
    STATUS_SUBJECT_DIFFICULTY_INACTIVE: '无效的'
}

# 题目抽取规则状态
STATUS_SUBJECT_CHOICE_RULE_ACTIVE = 1  # 有效的
STATUS_SUBJECT_CHOICE_RULE_INACTIVE = 2  # 无效的
STATUS_SUBJECT_CHOICE_RULE_LIST = [
    STATUS_SUBJECT_CHOICE_RULE_ACTIVE,
    STATUS_SUBJECT_CHOICE_RULE_INACTIVE
]
STATUS_SUBJECT_CHOICE_RULE_DICT = {
    STATUS_SUBJECT_CHOICE_RULE_ACTIVE: '有效的',
    STATUS_SUBJECT_CHOICE_RULE_INACTIVE: '无效的'
}

#  单位管理状态
STATUS_UNIT_MANAGER_ACTIVE = 1  # 有效的
STATUS_UNIT_MANAGER_INACTIVE = 2  # 无效的
STATUS_UNIT_MANAGER_LIST = [
    STATUS_UNIT_MANAGER_ACTIVE,
    STATUS_UNIT_MANAGER_INACTIVE
]
STATUS_UNIT_MANAGER_DICT = {
    STATUS_UNIT_MANAGER_ACTIVE: '有效的',
    STATUS_UNIT_MANAGER_INACTIVE: '无效的'
}

# 游戏关卡
STATUS_GAME_CHECK_POINT_ACTIVE = 1  # 启用的
STATUS_GAME_CHECK_POINT_INACTIVE = 2  # 禁用的
STATUS_GAME_CHECK_POINT_LIST = [
    STATUS_GAME_CHECK_POINT_ACTIVE,
    STATUS_GAME_CHECK_POINT_INACTIVE
]
STATUS_GAME_CHECK_POINT_DICT = {
    STATUS_GAME_CHECK_POINT_ACTIVE: '启用的',
    STATUS_GAME_CHECK_POINT_INACTIVE: '禁用的'
}

# 游戏段位
STATUS_GAME_DAN_GRADE_ACTIVE = 1  # 启用的
STATUS_GAME_DAN_GRADE_INACTIVE = 2  # 禁用的
STATUS_GAME_DAN_GRADE_LIST = [
    STATUS_GAME_DAN_GRADE_ACTIVE,
    STATUS_GAME_DAN_GRADE_INACTIVE
]
STATUS_GAME_DAN_GRADE_DICT = {
    STATUS_GAME_DAN_GRADE_ACTIVE: '启用的',
    STATUS_GAME_DAN_GRADE_INACTIVE: '禁用的'
}

# 错题本
STATUS_WRONG_SUBJECT_ACTIVE = 1  # 启用的
STATUS_WRONG_SUBJECT_INACTIVE = 2  # 禁用的
STATUS_WRONG_SUBJECT_LIST = [
    STATUS_WRONG_SUBJECT_ACTIVE,
    STATUS_WRONG_SUBJECT_INACTIVE
]
STATUS_WRONG_SUBJECT_DICT = {
    STATUS_WRONG_SUBJECT_ACTIVE: '启用的',
    STATUS_WRONG_SUBJECT_INACTIVE: '禁用的'
}

# 通知状态
STATUS_NOTICE_UNREAD = 1  # 未读
STATUS_NOTICE_READ = 2  # 已读
STATUS_NOTICE_LIST = [
    STATUS_NOTICE_UNREAD,
    STATUS_NOTICE_READ
]
STATUS_NOTICE_DICT = {
    STATUS_NOTICE_UNREAD: '未读',
    STATUS_NOTICE_READ: '已读'
}

# 通知类型
CATEGORY_NOTICE_FRIENDS_PLAY = 1  # 好友对战
CATEGORY_NOTICE_SYSTEM = 2  # 系统消息
CATEGORY_NOTICE_AWARD = 3  # 奖励信息
CATEGORY_NOTICE_OTHER = 99  # 其他
CATEGORY_NOTICE_LIST = [
    CATEGORY_NOTICE_FRIENDS_PLAY,
    CATEGORY_NOTICE_SYSTEM,
    CATEGORY_NOTICE_AWARD,
    CATEGORY_NOTICE_OTHER
]
CATEGORY_NOTICE_DICT = {
    CATEGORY_NOTICE_FRIENDS_PLAY: '好友对战',
    CATEGORY_NOTICE_SYSTEM: '系统消息',
    CATEGORY_NOTICE_AWARD: '奖励信息',
    CATEGORY_NOTICE_OTHER: '其他'
}

TYPE_MSG_LOTTERY = 1  # 抽奖通知
TYPE_MSG_DRAW = 2  # 领奖通知

# 用户来源状态
STATUS_MEMBER_SOURCE_ACTIVE = 1  # 启用的
STATUS_MEMBER_SOURCE_INACTIVE = 2  # 禁用的
STATUS_MEMBER_SOURCE_LIST = [
    STATUS_MEMBER_SOURCE_ACTIVE,
    STATUS_MEMBER_SOURCE_INACTIVE
]
STATUS_MEMBER_SOURCE_DICT = {
    STATUS_MEMBER_SOURCE_ACTIVE: '启用的',
    STATUS_MEMBER_SOURCE_INACTIVE: '禁用的'
}

CATEGORY_MEMBER_SHARE_EXAM_RESULT = 1
CATEGORY_MEMBER_SHARE_FRIEND_FIGHT = 2
CATEGORY_MEMBER_SHARE_OTHER = 3

CATEGORY_MEMBER_SHARE_LIST = [
    CATEGORY_MEMBER_SHARE_EXAM_RESULT,
    CATEGORY_MEMBER_SHARE_FRIEND_FIGHT,
    CATEGORY_MEMBER_SHARE_OTHER
]

CATEGORY_MEMBER_SHARE_DICT = {
    CATEGORY_MEMBER_SHARE_EXAM_RESULT: '答题结果分享',
    CATEGORY_MEMBER_SHARE_FRIEND_FIGHT: '好友对战分享',
    CATEGORY_MEMBER_SHARE_OTHER: '答题过程分享'
}

CATEGORY_MEMBER_LEARN_SUBJECT_WRONG = 1
CATEGORY_MEMBER_LEARN_SUBJECT_RESOLVING_VIEWED = 2
CATEGORY_MEMBER_LEARN_SUBJECT_RESOLVING_TREND = 3
CATEGORY_MEMBER_LEARN_SUBJECT_PERSONAL_CENTER = 4

CATEGORY_MEMBER_LEARN_LIST = [
    CATEGORY_MEMBER_LEARN_SUBJECT_WRONG,
    CATEGORY_MEMBER_LEARN_SUBJECT_RESOLVING_VIEWED,
    CATEGORY_MEMBER_LEARN_SUBJECT_RESOLVING_TREND,
    CATEGORY_MEMBER_LEARN_SUBJECT_PERSONAL_CENTER
]

CATEGORY_MEMBER_LEARN_DICT = {
    CATEGORY_MEMBER_LEARN_SUBJECT_WRONG: '错题本查看率',
    CATEGORY_MEMBER_LEARN_SUBJECT_RESOLVING_VIEWED: '答案解析查看率',
    CATEGORY_MEMBER_LEARN_SUBJECT_RESOLVING_TREND: '答案解析查看趋势',
    CATEGORY_MEMBER_LEARN_SUBJECT_PERSONAL_CENTER: '查看个人信息统计'
}

CATEGORY__RACE_AREA_PLAYER_QUANTITY = 1
CATEGORY__RACE_AREA_PLAYER_ACCURACY = 2
CATEGORY_RACE_AREA_CLEARANCE_QUANTITY = 3
CATEGORY_RACE_AREA_IMPORTANT_QUANTITY = 4
CATEGORY_RACE_AREA_IMPORTANT_PLAYER_ACCURACY = 5

CATEGORY_RACE_AREA__LIST = [
    CATEGORY__RACE_AREA_PLAYER_QUANTITY,
    CATEGORY__RACE_AREA_PLAYER_ACCURACY,
    CATEGORY_RACE_AREA_CLEARANCE_QUANTITY,
    CATEGORY_RACE_AREA_IMPORTANT_QUANTITY,
    CATEGORY_RACE_AREA_IMPORTANT_PLAYER_ACCURACY
]

CATEGORY_RACE_AREA_DICT = {
    CATEGORY__RACE_AREA_PLAYER_QUANTITY: '参与人数',
    CATEGORY__RACE_AREA_PLAYER_ACCURACY: '参与正确率',
    CATEGORY_RACE_AREA_CLEARANCE_QUANTITY: '通关人数',
    CATEGORY_RACE_AREA_IMPORTANT_QUANTITY: '重点人群参与人数',
    CATEGORY_RACE_AREA_IMPORTANT_PLAYER_ACCURACY: '重点人群正确率'
}

CATEGORY__RACE_COMPANY_PLAYER_QUANTITY = 1
CATEGORY__RACE_COMPANY_PLAYER_ACCURACY = 2
CATEGORY_RACE_COMPANY_CLEARANCE_QUANTITY = 3

CATEGORY_RACE_COMPANY__LIST = [
    CATEGORY__RACE_COMPANY_PLAYER_QUANTITY,
    CATEGORY__RACE_COMPANY_PLAYER_ACCURACY,
    CATEGORY_RACE_COMPANY_CLEARANCE_QUANTITY,
]

CATEGORY_RACE_COMPANY_DICT = {
    CATEGORY__RACE_COMPANY_PLAYER_QUANTITY: '参与人数',
    CATEGORY__RACE_COMPANY_PLAYER_ACCURACY: '参与正确率',
    CATEGORY_RACE_COMPANY_CLEARANCE_QUANTITY: '通关人数',
}

CATEGORY_EXAM_CERTIFICATE_PRIMARY = 1  # 新星(0-5)
CATEGORY_EXAM_CERTIFICATE_ADVANCED = 2  # 明星(6-10)
CATEGORY_EXAM_CERTIFICATE_SUPER = 3  # 巨星(11-16)
CATEGORY_EXAM_CERTIFICATE_LIST = [
    CATEGORY_EXAM_CERTIFICATE_PRIMARY,
    CATEGORY_EXAM_CERTIFICATE_ADVANCED,
    CATEGORY_EXAM_CERTIFICATE_SUPER
]
CATEGORY_EXAM_CERTIFICATE_DICT = {
    CATEGORY_EXAM_CERTIFICATE_PRIMARY: '新星',
    CATEGORY_EXAM_CERTIFICATE_ADVANCED: '明星',
    CATEGORY_EXAM_CERTIFICATE_SUPER: '巨星'
}

STATUS_RACE_ACTIVE = 1
STATUS_RACE_INACTIVE = 0

STATUS_RACE_LIST = [STATUS_RACE_ACTIVE, STATUS_RACE_INACTIVE]
STATUS_RACE_DICT = {
    STATUS_RACE_ACTIVE: '启用',
    STATUS_RACE_INACTIVE: '禁用'
}

# 作答最大时长
MAX_RESPOND_SECONDS = 20

STATUS_REDPACKET_AWARDED = 0  # 已被领取
STATUS_REDPACKET_NOT_AWARDED = 1  # 还没有被领取
STATUS_REDPACKET_AWARDING = 2  # 奖励发放
STATUS_REDPACKET_AWARD_FAILED = 5  # 领取失败
STATUS_REDPACKET_AWARD_LIST = [
    STATUS_REDPACKET_AWARDED, STATUS_REDPACKET_NOT_AWARDED, STATUS_REDPACKET_AWARDING, STATUS_REDPACKET_AWARD_FAILED
]

STATUS_REDPACKET_AWARD_DICT = {
    STATUS_REDPACKET_AWARDED: '已领取',
    STATUS_REDPACKET_NOT_AWARDED: '暂未领取',
    STATUS_REDPACKET_AWARDING: '发放中',
    STATUS_REDPACKET_AWARD_FAILED: '领取失败'
}

REDPACKET_REQUEST_STATUS_SUCCESS = 0  # 红包平台请求成功
REDPACKET_REQUEST_STATUS_ERROR = 1  # 红包平台请求错误
REDPACKET_REQUEST_STATUS_EMPTY = 2  # 红包发放时余额不足

STATUS_READPACKET_ISSUE_SUCCESS = 0  # 红包发放成功
STATUS_READPACKET_ISSUE_FAIL = 1  # 红包发放失败
STATUS_READPACKET_ISSUE_IN_PROCESS = 2  # 发放中

RESULT_RACE_LOTTERY_LOSE = 0  # 未中奖
RESULT_RACE_LOTTERY_WIN = 1  # 中奖
RESULT_RACE_LOTTERY_IN_PROCESS = 2  # 抽奖中
RESULT_RACE_LOTTERY_END = 3  # 已经参与过抽奖
RESULT_RACE_LOTTERY_OUT_OF_TIME = 4  # 抽奖超时
RESULT_RACE_LOTTERY_LOSE_LATE = 5  # 来晚了

CAN_SEE_ALL_RACE = 1  # 可以查看所有的竞赛活动
CAN_NOT_SEE_ALL_RACE = 2  # 不可以查看所有的竞赛活动

STATUS_INACTIVE = 0  # 禁用状态
STATUS_ACTIVE = 1  # 启用状态
STATUS_LIST = [STATUS_ACTIVE, STATUS_INACTIVE]
STATUS_DICT = {
    STATUS_ACTIVE: '启用',
    STATUS_INACTIVE: '禁用'
}

CATEGORY_REDPACKET_RULE_LOTTERY = 0  # 抽奖形式
CATEGORY_REDPACKET_RULE_DIRECT = 1  # 直接发放
CATEGORY_REDPACKET_RULE_LIST = [CATEGORY_REDPACKET_RULE_LOTTERY, CATEGORY_REDPACKET_RULE_DIRECT]
CATEGORY_REDPACKET_RULE_DICT = {
    CATEGORY_REDPACKET_RULE_LOTTERY: '抽奖形式', CATEGORY_REDPACKET_RULE_DIRECT: '直接发放'
}

CATEGORY_REDPACKET_CONST = 0  # 直接发放-固定数值
CATEGORY_REDPACKET_RANDOM = 1  # 直接发放-随机数值
CATEGORY_REDPACKET_LIST = [CATEGORY_REDPACKET_CONST, CATEGORY_REDPACKET_RANDOM]
CATEGORY_REDPACKET_DICT = {
    CATEGORY_REDPACKET_CONST: '固定红包', CATEGORY_REDPACKET_RANDOM: '随机红包'
}

STATUS_SUBJECT_STATISTICS_IN_PROCESS = 1  # 题目分析进行中
STATUS_SUBJECT_STATISTICS_END = 2  # 题目分析已结束

TEMP_LIU_AN_COMPANY_LIST = [
    '教育系统',
    '人民路小学',
    '三里桥小学',
    '皖西路小学',
    '梅山路小学',
    '清水河学校',
    '金安路学校',
    '人民路小学东校',
    '区卫健委',
    '市第四人民医院',
    '区妇幼保健院',
    '区疾控中心',
    '区卫生监督所',
    '区妇幼保健计划生育服务中心',
    '区直单位',
    '百大金商都购物中心'
]

CITY_NAME = "六安市"
CITY_RACE_CID = "CA755167DEA9AA89650D11C10FAA5413"

TEMP_LIU_AN_YU_AN_COMPANY_LIST = [
    '区教育系统',
    '区卫生系统'
]

MEMBER_TYPE_NORMAL = 1
MEMBER_TYPE_TEST = 2
MEMBER_TYPE_LIST = [MEMBER_TYPE_NORMAL, MEMBER_TYPE_TEST]
MEMBER_TYPE_DICT = {
    MEMBER_TYPE_NORMAL: '正常用户',
    MEMBER_TYPE_TEST: '测试用户'
}

TV_STATUS_ACTIVE=1
TV_STATUS_INACTIVE=0
TV_STATUS_LIST=[TV_STATUS_ACTIVE,TV_STATUS_INACTIVE]
TV_STATUS_DICT={
TV_STATUS_ACTIVE:'有效',
TV_STATUS_INACTIVE:'无效'
}